from __future__ import annotations

import logging
import os
from pathlib import Path

log = logging.getLogger(__name__)


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() not in ("0", "false", "no", "off")


def _env_csv(name: str, default: str = "") -> tuple[str, ...]:
    raw = os.getenv(name, default)
    return tuple(part.strip() for part in raw.split(",") if part.strip())


def _env_first(*names: str, default: str = "") -> str:
    for name in names:
        raw = os.getenv(name)
        if raw not in (None, ""):
            return raw
    return default


def _env_int_first(*names: str, default: int) -> int:
    raw = _env_first(*names, default=str(default))
    return int(raw)


def _env_float_first(*names: str, default: float) -> float:
    raw = _env_first(*names, default=str(default))
    return float(raw)


def _load_url_list(path: Path | None) -> tuple[str, ...]:
    if path is None:
        return ()
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        log.warning("URL list file not found: %s", path)
        return ()
    except OSError as exc:
        log.warning("URL list file could not be read: %s", exc)
        return ()
    urls: list[str] = []
    seen: set[str] = set()
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        url = line.split("#", 1)[0].strip()
        if not url or url in seen:
            continue
        seen.add(url)
        urls.append(url)
    return tuple(urls)


def _merge_csv_and_file_urls(csv_urls: tuple[str, ...], file_urls: tuple[str, ...]) -> tuple[str, ...]:
    urls: list[str] = []
    seen: set[str] = set()
    for url in (*csv_urls, *file_urls):
        clean = url.strip()
        if not clean or clean in seen:
            continue
        seen.add(clean)
        urls.append(clean)
    return tuple(urls)


def _load_dotenv(path: Path) -> None:
    """Minimal .env loader (no dependency). Existing env vars win."""
    if not path.exists():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # An empty value means "unset" — skip it so code defaults still apply
        # (e.g. `CG_CALLS_PER_MINUTE=` must not shadow the int default).
        if key and value:
            os.environ.setdefault(key, value)


_load_dotenv(Path(__file__).resolve().parent.parent / ".env")

TOP_N = int(os.getenv("RSI_TOP_N", "100"))
RSI_PERIOD = 14
RSI_OB = float(os.getenv("RSI_OB", "70"))
RSI_OS = float(os.getenv("RSI_OS", "30"))
LOOKBACK_DAYS_DAILY = 250  # >= REGIME_LONG_MA so the 200-day MA is available
LOOKBACK_DAYS_4H = 90
RSI_Z_WINDOW = 90
MIN_ANNUAL_VOL = 0.20

ADAPTIVE_OB_PERCENTILE = 95
ADAPTIVE_OS_PERCENTILE = 5

SEVERITY_TIERS = {
    "OB": [(90.0, "EXTREME"), (80.0, "ALERT"), (70.0, "WATCH")],
    "OS": [(10.0, "EXTREME"), (20.0, "ALERT"), (30.0, "WATCH")],
}

COOLDOWN_HOURS = float(os.getenv("RSI_COOLDOWN_HOURS", "48"))
MIN_CONVICTION_ALERT = int(os.getenv("RSI_MIN_CONVICTION", "0"))  # 0 = nothing dropped

# --- Approaching-threshold pre-alerts -------------------------------------
# A coin that hasn't crossed yet but is within APPROACH_MARGIN RSI points of
# its (effective) threshold AND moving toward it by at least APPROACH_MIN_DELTA
# over the delta window. Surfaces setups *before* they trigger.
APPROACH_MARGIN = float(os.getenv("RSI_APPROACH_MARGIN", "5"))
APPROACH_MIN_DELTA = float(os.getenv("RSI_APPROACH_MIN_DELTA", "3"))

# --- Tiered notification routing ------------------------------------------
# Nothing worth a look is dropped; tiering decides *how loud* it is.
#   INSTANT: sent immediately, prominent. Edge-triggered (newly crossed).
#   DIGEST:  batched watch-list snapshot, sent at most once per interval.
# A real OB/OS crossing is INSTANT if its severity is in INSTANT_SEVERITIES
# or its conviction >= INSTANT_CONVICTION; otherwise DIGEST. Pre-alerts are
# always DIGEST.
INSTANT_CONVICTION = int(os.getenv("RSI_INSTANT_CONVICTION", "65"))
INSTANT_SEVERITIES = {"EXTREME", "ALERT"}
DIGEST_INTERVAL_HOURS = float(os.getenv("RSI_DIGEST_INTERVAL_HOURS", "24"))

_CG_DEFAULT_CPM = "25" if os.getenv("COINGECKO_API_KEY") else "8"
CALLS_PER_MINUTE = int(os.getenv("CG_CALLS_PER_MINUTE", _CG_DEFAULT_CPM))
MAX_RETRIES = 5

VOLUME_AVG_WINDOW = 20
VOLUME_SPIKE_THRESHOLD = 1.5

BTC_CORR_WINDOW = 30
RSI_DELTA_WINDOW = 3
DIVERGENCE_LOOKBACK = 30
DIVERGENCE_ORDER = 5

# Trend regime (moving-average structure, close-only).
REGIME_SHORT_MA = 50
REGIME_LONG_MA = 200
REGIME_SLOPE_LOOKBACK = 20

# Signal outcome tracking: forward return measured N days after each crossing,
# computed from price history already fetched each scan (no extra API calls).
OUTCOME_HORIZONS = [1, 3, 7, 14]
OUTCOME_PRIMARY_HORIZON = 7  # horizon used for regime / conviction breakdowns

# Self-tuning conviction: let each (flag, regime) bucket's historical hit-rate
# nudge the conviction score. Needs enough matured samples to be trustworthy.
SELFTUNE_ENABLED = (os.getenv("RSI_SELFTUNE", "1").lower() not in ("0", "false", "no"))
SELFTUNE_MIN_SAMPLES = int(os.getenv("RSI_SELFTUNE_MIN_SAMPLES", "8"))
SELFTUNE_MAX_SWING = int(os.getenv("RSI_SELFTUNE_MAX_SWING", "15"))

# Market-regime gating: each setup only has edge in specific BTC market regimes
# defined in signal_registry.py. The registry now seeds conviction from measured
# edge priors; this flag controls whether the current market regime is used for
# alignment/routing. MARKET_ALIGN_SWING is retained for the legacy helper/tests.
MARKET_GATING_ENABLED = (os.getenv("RSI_MARKET_GATING", "1").lower() not in ("0", "false", "no"))
MARKET_ALIGN_SWING = int(os.getenv("RSI_MARKET_ALIGN_SWING", "12"))

# Paper-trading scoreboard: auto-open a virtual trade on each new OB/OS crossing
# (long if the setup expects up, short if down), close it after PAPER_HOLD_DAYS
# at that day's close, and track realized P&L — the live proof of whether the
# gated signals make money. No real orders; uses prices already fetched.
PAPER_TRADING_ENABLED = (os.getenv("RSI_PAPER", "1").lower() not in ("0", "false", "no"))
PAPER_HOLD_DAYS = int(os.getenv("RSI_PAPER_HOLD_DAYS", str(OUTCOME_PRIMARY_HORIZON)))

# Sell-the-news / proxy-catalyst event fade research sleeve. Disabled by
# default and alert-only when enabled; no live order execution exists.
EVENT_FADE_ENABLED = _env_bool("RSI_EVENT_FADE_ENABLED", False)
EVENT_FADE_MODE = os.getenv("RSI_EVENT_FADE_MODE", "alert_only")
_EVENT_FADE_EVENTS_PATH_RAW = os.getenv("RSI_EVENT_FADE_EVENTS_PATH", "")
EVENT_FADE_MIN_WATCHLIST_SCORE = int(os.getenv("RSI_EVENT_FADE_MIN_WATCHLIST_SCORE", "60"))
EVENT_FADE_MIN_ARMED_SCORE = int(os.getenv("RSI_EVENT_FADE_MIN_ARMED_SCORE", "75"))
EVENT_FADE_MIN_TRIGGER_SCORE = int(os.getenv("RSI_EVENT_FADE_MIN_TRIGGER_SCORE", "80"))
EVENT_FADE_MIN_EVENT_CONFIDENCE = float(os.getenv("RSI_EVENT_FADE_MIN_EVENT_CONFIDENCE", "0.80"))
EVENT_FADE_MAX_DAYS_TO_EVENT = float(os.getenv("RSI_EVENT_FADE_MAX_DAYS_TO_EVENT", "7"))
EVENT_FADE_EXPIRE_HOURS_AFTER_EVENT = float(os.getenv("RSI_EVENT_FADE_EXPIRE_HOURS_AFTER_EVENT", "72"))
EVENT_FADE_MIN_RETURN_24H = float(os.getenv("RSI_EVENT_FADE_MIN_RETURN_24H", "0.75"))
EVENT_FADE_MIN_RETURN_7D = float(os.getenv("RSI_EVENT_FADE_MIN_RETURN_7D", "1.50"))
EVENT_FADE_EXTREME_RETURN_7D = float(os.getenv("RSI_EVENT_FADE_EXTREME_RETURN_7D", "5.00"))
EVENT_FADE_MIN_VOLUME_Z = float(os.getenv("RSI_EVENT_FADE_MIN_VOLUME_Z", "3.0"))
EVENT_FADE_MIN_OI_CHANGE_24H = float(os.getenv("RSI_EVENT_FADE_MIN_OI_CHANGE_24H", "0.30"))
EVENT_FADE_HOT_FUNDING_8H = float(os.getenv("RSI_EVENT_FADE_HOT_FUNDING_8H", "0.0005"))
EVENT_FADE_EXTREME_FUNDING_8H = float(os.getenv("RSI_EVENT_FADE_EXTREME_FUNDING_8H", "0.0010"))
EVENT_FADE_MIN_PERP_SPOT_VOLUME_RATIO = float(os.getenv("RSI_EVENT_FADE_MIN_PERP_SPOT_VOLUME_RATIO", "5.0"))
EVENT_FADE_MIN_RSI_OVERBOUGHT_SCORE = float(os.getenv("RSI_EVENT_FADE_MIN_RSI_OVERBOUGHT_SCORE", "60"))
EVENT_FADE_BLOCK_BTC_STRONG_RISK_ON = _env_bool("RSI_EVENT_FADE_BLOCK_BTC_STRONG_RISK_ON", True)
EVENT_FADE_MAX_SPREAD_BPS = float(os.getenv("RSI_EVENT_FADE_MAX_SPREAD_BPS", "100"))
EVENT_FADE_MIN_DEPTH_2PCT_USD = float(os.getenv("RSI_EVENT_FADE_MIN_DEPTH_2PCT_USD", "10000"))
EVENT_FADE_DEFAULT_RISK_PCT = float(os.getenv("RSI_EVENT_FADE_DEFAULT_RISK_PCT", "0.005"))
EVENT_FADE_MAX_RISK_PCT = float(os.getenv("RSI_EVENT_FADE_MAX_RISK_PCT", "0.01"))
EVENT_FADE_MAX_LEVERAGE_HINT = float(os.getenv("RSI_EVENT_FADE_MAX_LEVERAGE_HINT", "2.0"))
EVENT_FADE_MIN_FAILURE_CHECKS = int(os.getenv("RSI_EVENT_FADE_MIN_FAILURE_CHECKS", "2"))
EVENT_FADE_ALLOW_PROXY_VENUE_TRIGGER = _env_bool("RSI_EVENT_FADE_ALLOW_PROXY_VENUE_TRIGGER", False)

# Automatic event-discovery radar. This remains research-only: no live routing,
# no paper trades, no DB writes, no execution. Providers are fixture-backed by
# default; live source fetches must be explicitly opted in per provider.
EVENT_RESEARCH_NOW = os.getenv("RSI_EVENT_RESEARCH_NOW", "").strip() or None
EVENT_DISCOVERY_ENABLED = _env_bool("RSI_EVENT_DISCOVERY_ENABLED", False)
EVENT_DISCOVERY_MODE = os.getenv("RSI_EVENT_DISCOVERY_MODE", "research_only")
_EVENT_DISCOVERY_EVENTS_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_EVENTS_PATH", "")
_EVENT_DISCOVERY_ALIASES_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_ALIASES_PATH",
    "event_discovery_aliases.json",
)
_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH",
    "",
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_LIVE = _env_bool("RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_LIVE", False)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_API_KEY = os.getenv("RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_API_KEY", "")
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_API_SECRET = os.getenv(
    "RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_API_SECRET",
    "",
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_WS_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_WS_URL",
    "wss://api.binance.com/sapi/wss",
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_TOPIC = os.getenv(
    "RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_TOPIC",
    "com_announcement_en",
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_RECV_WINDOW_MS = int(
    os.getenv("RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_RECV_WINDOW_MS", "30000")
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_LISTEN_SECONDS = float(
    os.getenv("RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_LISTEN_SECONDS", "5")
)
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_MAX_MESSAGES = int(
    os.getenv("RSI_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_MAX_MESSAGES", "20")
)
_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH",
    "",
)
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LIVE = _env_bool("RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LIVE", False)
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_BASE_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_BASE_URL",
    "https://api.bybit.com",
)
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LOCALE = os.getenv(
    "RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LOCALE",
    "en-US",
)
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_TYPE = os.getenv(
    "RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_TYPE",
    "new_crypto",
)
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LIMIT = int(os.getenv("RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_LIMIT", "20"))
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_TIMEOUT = float(
    os.getenv("RSI_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_TIMEOUT", "10")
)
_EVENT_DISCOVERY_COINMARKETCAL_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_COINMARKETCAL_PATH", "")
_EVENT_DISCOVERY_TOKENOMIST_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_TOKENOMIST_PATH", "")
_EVENT_DISCOVERY_CRYPTOPANIC_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_PATH", "")
EVENT_DISCOVERY_CRYPTOPANIC_LIVE = _env_bool("RSI_EVENT_DISCOVERY_CRYPTOPANIC_LIVE", False)
EVENT_DISCOVERY_CRYPTOPANIC_API_TOKEN = _env_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_API_TOKEN",
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_AUTH_TOKEN",
    "CRYPTOPANIC_AUTH_TOKEN",
    "CRYPTOPANIC_API_KEY",
    "CRYPTOPANIC_TOKEN",
)
EVENT_DISCOVERY_CRYPTOPANIC_BASE_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_BASE_URL",
    "https://cryptopanic.com/api/growth_weekly/v2",
)
EVENT_DISCOVERY_CRYPTOPANIC_PLAN = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_PLAN", "growth_weekly")
EVENT_DISCOVERY_CRYPTOPANIC_PUBLIC = _env_bool("RSI_EVENT_DISCOVERY_CRYPTOPANIC_PUBLIC", True)
EVENT_DISCOVERY_CRYPTOPANIC_FOLLOWING = _env_bool("RSI_EVENT_DISCOVERY_CRYPTOPANIC_FOLLOWING", False)
EVENT_DISCOVERY_CRYPTOPANIC_FILTER = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_FILTER", "")
EVENT_DISCOVERY_CRYPTOPANIC_CURRENCIES = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_CURRENCIES", "")
EVENT_DISCOVERY_CRYPTOPANIC_REGIONS = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_REGIONS", "en")
EVENT_DISCOVERY_CRYPTOPANIC_KIND = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_KIND", "news")
EVENT_DISCOVERY_CRYPTOPANIC_SEARCH = os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_SEARCH", "")
EVENT_DISCOVERY_CRYPTOPANIC_TIMEOUT = float(os.getenv("RSI_EVENT_DISCOVERY_CRYPTOPANIC_TIMEOUT", "10"))
_EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH",
    "",
)
EVENT_DISCOVERY_CRYPTOPANIC_WEEKLY_REQUEST_LIMIT = _env_int_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_WEEKLY_REQUEST_LIMIT",
    "CRYPTOPANIC_WEEKLY_REQUEST_LIMIT",
    default=600,
)
EVENT_DISCOVERY_CRYPTOPANIC_REQUESTS_PER_RUN_LIMIT = _env_int_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_REQUESTS_PER_RUN_LIMIT",
    "CRYPTOPANIC_REQUESTS_PER_RUN_LIMIT",
    default=10,
)
EVENT_DISCOVERY_CRYPTOPANIC_REQUESTS_PER_DAY_SOFT_LIMIT = _env_int_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_REQUESTS_PER_DAY_SOFT_LIMIT",
    "CRYPTOPANIC_REQUESTS_PER_DAY_SOFT_LIMIT",
    default=80,
)
EVENT_DISCOVERY_CRYPTOPANIC_MIN_SECONDS_BETWEEN_REQUESTS = _env_float_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_MIN_SECONDS_BETWEEN_REQUESTS",
    "CRYPTOPANIC_MIN_SECONDS_BETWEEN_REQUESTS",
    default=1.0,
)
EVENT_DISCOVERY_CRYPTOPANIC_MAX_PAGES_PER_QUERY = _env_int_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_MAX_PAGES_PER_QUERY",
    "CRYPTOPANIC_MAX_PAGES_PER_QUERY",
    default=1,
)
EVENT_DISCOVERY_CRYPTOPANIC_MAX_CURRENCIES_PER_REQUEST = _env_int_first(
    "RSI_EVENT_DISCOVERY_CRYPTOPANIC_MAX_CURRENCIES_PER_REQUEST",
    "CRYPTOPANIC_MAX_CURRENCIES_PER_REQUEST",
    default=10,
)
_EVENT_DISCOVERY_GDELT_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_GDELT_PATH", "")
EVENT_DISCOVERY_GDELT_LIVE = _env_bool("RSI_EVENT_DISCOVERY_GDELT_LIVE", False)
EVENT_DISCOVERY_GDELT_BASE_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_GDELT_BASE_URL",
    "https://api.gdeltproject.org/api/v2/doc/doc",
)
EVENT_DISCOVERY_GDELT_QUERY = os.getenv(
    "RSI_EVENT_DISCOVERY_GDELT_QUERY",
    '("pre-ipo" OR "pre ipo" OR "synthetic exposure" OR "tokenized stock" '
    'OR "prediction market" OR "fan token")',
)
EVENT_DISCOVERY_GDELT_MAX_RECORDS = int(os.getenv("RSI_EVENT_DISCOVERY_GDELT_MAX_RECORDS", "50"))
EVENT_DISCOVERY_GDELT_TIMEOUT = float(os.getenv("RSI_EVENT_DISCOVERY_GDELT_TIMEOUT", "10"))
_EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH", "")
EVENT_DISCOVERY_PROJECT_BLOG_RSS_LIVE = _env_bool("RSI_EVENT_DISCOVERY_PROJECT_BLOG_RSS_LIVE", False)
_EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS = _env_csv("RSI_EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS")
_EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH",
    "",
)
EVENT_DISCOVERY_PROJECT_BLOG_RSS_TIMEOUT = float(os.getenv("RSI_EVENT_DISCOVERY_PROJECT_BLOG_RSS_TIMEOUT", "10"))
_EVENT_DISCOVERY_EXTERNAL_IPO_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_EXTERNAL_IPO_PATH", "")
_EVENT_DISCOVERY_SPORTS_FIXTURES_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_SPORTS_FIXTURES_PATH", "")
_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH",
    "",
)
EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_LIVE = _env_bool(
    "RSI_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_LIVE",
    False,
)
EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_BASE_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_BASE_URL",
    "https://gamma-api.polymarket.com/events",
)
EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_LIMIT = int(
    os.getenv("RSI_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_LIMIT", "100")
)
EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_TIMEOUT = float(
    os.getenv("RSI_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_TIMEOUT", "10")
)
_EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH_RAW = os.getenv(
    "RSI_EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH",
    "",
)
EVENT_DISCOVERY_COINALYZE_LIVE = _env_bool("RSI_EVENT_DISCOVERY_COINALYZE_LIVE", False)
EVENT_DISCOVERY_COINALYZE_API_KEY = os.getenv("RSI_EVENT_DISCOVERY_COINALYZE_API_KEY", "")
EVENT_DISCOVERY_COINALYZE_SYMBOLS = _env_csv("RSI_EVENT_DISCOVERY_COINALYZE_SYMBOLS")
EVENT_DISCOVERY_COINALYZE_AUTO_SYMBOLS = _env_bool("RSI_EVENT_DISCOVERY_COINALYZE_AUTO_SYMBOLS", True)
EVENT_DISCOVERY_COINALYZE_BASE_URL = os.getenv(
    "RSI_EVENT_DISCOVERY_COINALYZE_BASE_URL",
    "https://api.coinalyze.net/v1/",
)
EVENT_DISCOVERY_COINALYZE_TIMEOUT = float(os.getenv("RSI_EVENT_DISCOVERY_COINALYZE_TIMEOUT", "10"))
EVENT_DISCOVERY_COINALYZE_HISTORY_INTERVAL = os.getenv(
    "RSI_EVENT_DISCOVERY_COINALYZE_HISTORY_INTERVAL",
    "1hour",
)
EVENT_DISCOVERY_COINALYZE_LOOKBACK_HOURS = int(os.getenv("RSI_EVENT_DISCOVERY_COINALYZE_LOOKBACK_HOURS", "24"))
EVENT_DISCOVERY_COINALYZE_CONVERT_TO_USD = _env_bool("RSI_EVENT_DISCOVERY_COINALYZE_CONVERT_TO_USD", True)
_EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH", "")
_EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH", "")
_EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH", "")
_EVENT_DISCOVERY_DUNE_SUPPLY_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_DUNE_SUPPLY_PATH", "")
_EVENT_DISCOVERY_UNIVERSE_PATH_RAW = os.getenv("RSI_EVENT_DISCOVERY_UNIVERSE_PATH", "")
_EVENT_ASSET_REGISTRY_PATH_RAW = os.getenv(
    "RSI_EVENT_ASSET_REGISTRY_PATH",
    "fixtures/event_discovery/asset_registry.json",
)
_EVENT_DISCOVERY_CACHE_DIR_RAW = os.getenv("RSI_EVENT_DISCOVERY_CACHE_DIR", "event_fade_cache")
EVENT_DISCOVERY_LOOKBACK_HOURS = int(os.getenv("RSI_EVENT_DISCOVERY_LOOKBACK_HOURS", "72"))
EVENT_DISCOVERY_HORIZON_DAYS = int(os.getenv("RSI_EVENT_DISCOVERY_HORIZON_DAYS", "14"))
EVENT_DISCOVERY_UNIVERSE_LIMIT = int(os.getenv("RSI_EVENT_DISCOVERY_UNIVERSE_LIMIT", "0"))
EVENT_DISCOVERY_UNIVERSE_LIVE = _env_bool("RSI_EVENT_DISCOVERY_UNIVERSE_LIVE", False)
EVENT_DISCOVERY_UNIVERSE_FETCH_LIMIT = int(os.getenv("RSI_EVENT_DISCOVERY_UNIVERSE_FETCH_LIMIT", "0"))
EVENT_DISCOVERY_MIN_LINK_CONFIDENCE = float(os.getenv("RSI_EVENT_DISCOVERY_MIN_LINK_CONFIDENCE", "0.80"))
EVENT_DISCOVERY_MIN_CLASSIFIER_CONFIDENCE = float(os.getenv("RSI_EVENT_DISCOVERY_MIN_CLASSIFIER_CONFIDENCE", "0.80"))
EVENT_DISCOVERY_MIN_EVENT_TIME_CONFIDENCE = float(os.getenv("RSI_EVENT_DISCOVERY_MIN_EVENT_TIME_CONFIDENCE", "0.80"))

# Event-discovery research alerts. Disabled by default and separate from normal
# RSI routing, event-fade validation labels, paper trades, and execution.
EVENT_ALERTS_ENABLED = _env_bool("RSI_EVENT_ALERTS_ENABLED", False)
EVENT_ALERT_MODE = os.getenv("RSI_EVENT_ALERT_MODE", "research_only")
EVENT_ALERT_MIN_DIGEST_SCORE = int(os.getenv("RSI_EVENT_ALERT_MIN_DIGEST_SCORE", "55"))
EVENT_ALERT_MIN_WATCHLIST_SCORE = int(os.getenv("RSI_EVENT_ALERT_MIN_WATCHLIST_SCORE", "70"))
EVENT_ALERT_MIN_HIGH_PRIORITY_SCORE = int(os.getenv("RSI_EVENT_ALERT_MIN_HIGH_PRIORITY_SCORE", "80"))
EVENT_ALERT_MAX_DIGEST_ITEMS = int(os.getenv("RSI_EVENT_ALERT_MAX_DIGEST_ITEMS", "10"))
EVENT_ALERT_MAX_INSTANT_PER_DAY = int(os.getenv("RSI_EVENT_ALERT_MAX_INSTANT_PER_DAY", "3"))
EVENT_ALERT_COOLDOWN_HOURS = float(os.getenv("RSI_EVENT_ALERT_COOLDOWN_HOURS", "12"))
EVENT_ALERT_ALLOW_PROXY_VENUE = _env_bool("RSI_EVENT_ALERT_ALLOW_PROXY_VENUE", False)

# Event-discovery LLM relationship analysis. Shadow-only by default: no normal
# RSI alert routing, Telegram sends, paper trades, live DB writes, or execution.
EVENT_LLM_ENABLED = _env_bool("RSI_EVENT_LLM_ENABLED", False)
EVENT_LLM_MODE = os.getenv("RSI_EVENT_LLM_MODE", "shadow")
EVENT_LLM_PROVIDER = os.getenv("RSI_EVENT_LLM_PROVIDER", "fixture")
EVENT_LLM_MODEL = os.getenv("RSI_EVENT_LLM_MODEL", "") or None
EVENT_LLM_OPENAI_TIMEOUT = float(os.getenv("RSI_EVENT_LLM_OPENAI_TIMEOUT", "30"))
EVENT_LLM_MAX_CANDIDATES_PER_RUN = int(os.getenv("RSI_EVENT_LLM_MAX_CANDIDATES_PER_RUN", "20"))
EVENT_LLM_MIN_PREFILTER_SCORE = int(os.getenv("RSI_EVENT_LLM_MIN_PREFILTER_SCORE", "45"))
EVENT_LLM_REQUIRE_EVIDENCE_QUOTES = _env_bool("RSI_EVENT_LLM_REQUIRE_EVIDENCE_QUOTES", True)
EVENT_LLM_MAX_PARALLEL_CALLS = int(os.getenv("RSI_EVENT_LLM_MAX_PARALLEL_CALLS", "1"))
EVENT_LLM_MAX_CALLS_PER_RUN = int(os.getenv("RSI_EVENT_LLM_MAX_CALLS_PER_RUN", "0"))
EVENT_LLM_MAX_CALLS_PER_DAY = int(os.getenv("RSI_EVENT_LLM_MAX_CALLS_PER_DAY", "0"))
EVENT_LLM_MAX_ESTIMATED_COST_USD_PER_DAY = float(os.getenv("RSI_EVENT_LLM_MAX_ESTIMATED_COST_USD_PER_DAY", "0"))
EVENT_LLM_ESTIMATED_COST_PER_CALL_USD = float(os.getenv("RSI_EVENT_LLM_ESTIMATED_COST_PER_CALL_USD", "0"))
EVENT_LLM_CACHE_TTL_HOURS = float(os.getenv("RSI_EVENT_LLM_CACHE_TTL_HOURS", "0"))
_EVENT_LLM_CACHE_PATH_RAW = os.getenv("RSI_EVENT_LLM_CACHE_PATH", "")
_EVENT_LLM_BUDGET_LEDGER_PATH_RAW = os.getenv("RSI_EVENT_LLM_BUDGET_LEDGER_PATH", "")
EVENT_LLM_PROMPT_VERSION = os.getenv("RSI_EVENT_LLM_PROMPT_VERSION", "llm_proxy_context_v1")

# Event-discovery LLM raw-event extraction. Disabled by default and
# research-only; extracted assets are proposals until deterministic resolver
# validation matches a known asset universe/alias.
EVENT_LLM_EXTRACTOR_ENABLED = _env_bool("RSI_EVENT_LLM_EXTRACTOR_ENABLED", False)
EVENT_LLM_EXTRACTOR_MODE = os.getenv("RSI_EVENT_LLM_EXTRACTOR_MODE", "shadow")
EVENT_LLM_EXTRACTOR_PROVIDER = os.getenv("RSI_EVENT_LLM_EXTRACTOR_PROVIDER", EVENT_LLM_PROVIDER)
EVENT_LLM_EXTRACTOR_MODEL = os.getenv("RSI_EVENT_LLM_EXTRACTOR_MODEL", "") or EVENT_LLM_MODEL
EVENT_LLM_EXTRACTOR_OPENAI_TIMEOUT = float(
    os.getenv("RSI_EVENT_LLM_EXTRACTOR_OPENAI_TIMEOUT", str(EVENT_LLM_OPENAI_TIMEOUT))
)
EVENT_LLM_EXTRACTOR_MAX_EVENTS_PER_RUN = int(os.getenv("RSI_EVENT_LLM_EXTRACTOR_MAX_EVENTS_PER_RUN", "50"))
EVENT_LLM_EXTRACTOR_REQUIRE_EVIDENCE_QUOTES = _env_bool("RSI_EVENT_LLM_EXTRACTOR_REQUIRE_EVIDENCE_QUOTES", True)
_EVENT_LLM_EXTRACTOR_CACHE_PATH_RAW = os.getenv("RSI_EVENT_LLM_EXTRACTOR_CACHE_PATH", "")
EVENT_LLM_EXTRACTOR_PROMPT_VERSION = os.getenv("RSI_EVENT_LLM_EXTRACTOR_PROMPT_VERSION", "llm_raw_event_extraction_v1")

# Optional LLM catalyst-frame parser. Disabled by default; it can only produce
# quote-validated research metadata for deterministic incident/impact logic.
EVENT_LLM_CATALYST_FRAMES_ENABLED = _env_bool("RSI_EVENT_LLM_CATALYST_FRAMES_ENABLED", False)
EVENT_LLM_CATALYST_FRAMES_PROVIDER = os.getenv("RSI_EVENT_LLM_CATALYST_FRAMES_PROVIDER", EVENT_LLM_PROVIDER)
EVENT_LLM_CATALYST_FRAMES_MODEL = os.getenv("RSI_EVENT_LLM_CATALYST_FRAMES_MODEL", "") or EVENT_LLM_MODEL
EVENT_LLM_CATALYST_FRAMES_MAX_ROWS_PER_RUN = int(os.getenv("RSI_EVENT_LLM_CATALYST_FRAMES_MAX_ROWS_PER_RUN", "20"))
EVENT_LLM_CATALYST_FRAMES_MIN_SOURCE_SCORE = float(os.getenv("RSI_EVENT_LLM_CATALYST_FRAMES_MIN_SOURCE_SCORE", "0.50"))
EVENT_LLM_CATALYST_FRAMES_USE_ENRICHED_TEXT = _env_bool("RSI_EVENT_LLM_CATALYST_FRAMES_USE_ENRICHED_TEXT", True)
EVENT_LLM_CATALYST_FRAMES_ONLY_AMBIGUOUS = _env_bool("RSI_EVENT_LLM_CATALYST_FRAMES_ONLY_AMBIGUOUS", True)
EVENT_LLM_CATALYST_FRAMES_PROMPT_VERSION = os.getenv("RSI_EVENT_LLM_CATALYST_FRAMES_PROMPT_VERSION", "llm_catalyst_frames_v1")
_EVENT_WATCHLIST_STATE_PATH_RAW = os.getenv("RSI_EVENT_WATCHLIST_STATE_PATH", "")
_EVENT_WATCHLIST_MONITOR_MARKET_PATH_RAW = os.getenv("RSI_EVENT_WATCHLIST_MONITOR_MARKET_PATH", "")
_EVENT_ALPHA_FEEDBACK_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_FEEDBACK_PATH", "")
_EVENT_ALPHA_ALERT_STORE_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_ALERT_STORE_PATH", "")
_EVENT_ALPHA_NOTIFICATION_RUNS_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_NOTIFICATION_RUNS_PATH", "")
_EVENT_ALPHA_RUN_LEDGER_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_RUN_LEDGER_PATH", "")
_EVENT_ALPHA_MISSED_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_MISSED_PATH", "")
_EVENT_ALPHA_PRIORS_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_PRIORS_PATH", "")
_EVENT_ALPHA_OUTCOMES_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_OUTCOMES_PATH", "")
_EVENT_PROVIDER_HEALTH_PATH_RAW = os.getenv("RSI_EVENT_PROVIDER_HEALTH_PATH", "")
_EVENT_ALPHA_DAILY_BRIEF_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_DAILY_BRIEF_PATH", "")
_EVENT_IMPACT_HYPOTHESIS_STORE_PATH_RAW = os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_STORE_PATH", "")
_EVENT_CORE_OPPORTUNITY_STORE_PATH_RAW = os.getenv("RSI_EVENT_CORE_OPPORTUNITY_STORE_PATH", "")
_EVENT_INCIDENT_STORE_PATH_RAW = os.getenv("RSI_EVENT_INCIDENT_STORE_PATH", "")
_EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH_RAW = os.getenv("RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH", "")
EVENT_INCIDENT_STORE_DIAGNOSTIC = _env_bool("RSI_EVENT_INCIDENT_STORE_DIAGNOSTIC", False)
EVENT_INCIDENT_STORE_RAW_OBSERVATIONS = _env_bool("RSI_EVENT_INCIDENT_STORE_RAW_OBSERVATIONS", False)
_EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR_RAW = os.getenv("RSI_EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR", "")
_EVENT_RESEARCH_CARDS_DIR_RAW = os.getenv("RSI_EVENT_RESEARCH_CARDS_DIR", "")
_EVENT_ALPHA_ARTIFACT_BASE_DIR_RAW = os.getenv("RSI_EVENT_ALPHA_ARTIFACT_BASE_DIR", "")
EVENT_ALPHA_ARTIFACT_NAMESPACE = os.getenv("RSI_EVENT_ALPHA_ARTIFACT_NAMESPACE", "")
EVENT_ALPHA_RUN_MODE = os.getenv("RSI_EVENT_ALPHA_RUN_MODE", "")
EVENT_ALPHA_ARTIFACT_DOCTOR_STRICT = _env_bool("RSI_EVENT_ALPHA_ARTIFACT_DOCTOR_STRICT", False)
EVENT_ALPHA_SNAPSHOT_POLICY = os.getenv("RSI_EVENT_ALPHA_SNAPSHOT_POLICY", "all")
EVENT_ALPHA_SNAPSHOT_SAMPLED_CONTROLS = int(os.getenv("RSI_EVENT_ALPHA_SNAPSHOT_SAMPLED_CONTROLS", "25"))
_EVENT_CATALYST_SEARCH_FIXTURE_PATH_RAW = os.getenv("RSI_EVENT_CATALYST_SEARCH_FIXTURE_PATH", "")
_EVENT_IMPACT_TAXONOMY_PATH_RAW = os.getenv(
    "RSI_EVENT_IMPACT_TAXONOMY_PATH",
    "fixtures/event_discovery/event_impact_taxonomy.json",
)
EVENT_SOURCE_ENRICHMENT_ENABLED = _env_bool("RSI_EVENT_SOURCE_ENRICHMENT_ENABLED", False)
_EVENT_SOURCE_ENRICHMENT_CACHE_DIR_RAW = os.getenv("RSI_EVENT_SOURCE_ENRICHMENT_CACHE_DIR", "")
EVENT_SOURCE_ENRICHMENT_MAX_CHARS = int(os.getenv("RSI_EVENT_SOURCE_ENRICHMENT_MAX_CHARS", "12000"))
EVENT_SOURCE_ENRICHMENT_TIMEOUT_SECONDS = float(os.getenv("RSI_EVENT_SOURCE_ENRICHMENT_TIMEOUT_SECONDS", "10"))
EVENT_SOURCE_ENRICHMENT_MAX_ROWS_PER_RUN = int(os.getenv("RSI_EVENT_SOURCE_ENRICHMENT_MAX_ROWS_PER_RUN", "0"))
EVENT_SOURCE_ENRICHMENT_MIN_SOURCE_CONFIDENCE = float(
    os.getenv("RSI_EVENT_SOURCE_ENRICHMENT_MIN_SOURCE_CONFIDENCE", "0.55")
)
EVENT_SOURCE_ENRICHMENT_CLEANER_VERSION = os.getenv(
    "RSI_EVENT_SOURCE_ENRICHMENT_CLEANER_VERSION",
    "source_enrichment_cleaner_v2",
)

# Event Alpha Radar research phases. Market enrichment, anomaly scanning,
# watchlist state, local router decisions, and feedback artifacts are implemented
# but disabled/explicit by default; they remain artifact/report paths until
# explicitly promoted.
EVENT_MARKET_ENRICHMENT_ENABLED = _env_bool("RSI_EVENT_MARKET_ENRICHMENT_ENABLED", False)
EVENT_MARKET_CONTEXT_MAX_AGE_HOURS = float(os.getenv("RSI_EVENT_MARKET_CONTEXT_MAX_AGE_HOURS", "6"))
EVENT_MARKET_CONTEXT_ALLOW_STALE_FIXTURE = _env_bool("RSI_EVENT_MARKET_CONTEXT_ALLOW_STALE_FIXTURE", False)
EVENT_MARKET_CONTEXT_STALE_CAP_LEVEL = os.getenv("RSI_EVENT_MARKET_CONTEXT_STALE_CAP_LEVEL", "weak")
EVENT_ANOMALY_SCANNER_ENABLED = _env_bool("RSI_EVENT_ANOMALY_SCANNER_ENABLED", False)
EVENT_ANOMALY_MIN_RETURN_24H = float(os.getenv("RSI_EVENT_ANOMALY_MIN_RETURN_24H", "0.30"))
EVENT_ANOMALY_MIN_VOLUME_MCAP = float(os.getenv("RSI_EVENT_ANOMALY_MIN_VOLUME_MCAP", "0.25"))
EVENT_ANOMALY_MIN_VOLUME_ZSCORE = float(os.getenv("RSI_EVENT_ANOMALY_MIN_VOLUME_ZSCORE", "3.0"))
EVENT_ANOMALY_MAX_ASSETS = int(os.getenv("RSI_EVENT_ANOMALY_MAX_ASSETS", "50"))
_EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH",
    "fixtures/event_market_anomaly/market_rows.json",
)
EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH = Path(_EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH_RAW).expanduser()
EVENT_ALPHA_MARKET_ANOMALY_MAX_ASSETS = int(os.getenv("RSI_EVENT_ALPHA_MARKET_ANOMALY_MAX_ASSETS", "50"))
EVENT_ALPHA_MARKET_ANOMALY_SUSPICIOUS_LIQUIDITY_USD = float(
    os.getenv("RSI_EVENT_ALPHA_MARKET_ANOMALY_SUSPICIOUS_LIQUIDITY_USD", "50000")
)
_EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH",
    "fixtures/event_discovery/official_exchange_binance_announcements.json",
)
_EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH",
    "fixtures/event_discovery/official_exchange_bybit_announcements.json",
)
EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH = Path(_EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH_RAW).expanduser()
EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH = Path(_EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH_RAW).expanduser()
_EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH",
    "fixtures/event_discovery/scheduled_tokenomist_unlocks.json",
)
_EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH",
    "fixtures/event_discovery/scheduled_messari_unlocks.json",
)
_EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH",
    "fixtures/event_discovery/scheduled_coinmarketcal_events.json",
)
EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH = Path(_EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH_RAW).expanduser()
EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH = Path(_EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH_RAW).expanduser()
EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH = Path(_EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH_RAW).expanduser()
_EVENT_ALPHA_DERIVATIVES_CROWDING_PATH_RAW = os.getenv(
    "RSI_EVENT_ALPHA_DERIVATIVES_CROWDING_PATH",
    "fixtures/event_derivatives_crowding/derivatives_crowding_rows.json",
)
EVENT_ALPHA_DERIVATIVES_CROWDING_PATH = Path(_EVENT_ALPHA_DERIVATIVES_CROWDING_PATH_RAW).expanduser()
EVENT_CATALYST_SEARCH_ENABLED = _env_bool("RSI_EVENT_CATALYST_SEARCH_ENABLED", False)
EVENT_CATALYST_SEARCH_PROVIDER = os.getenv("RSI_EVENT_CATALYST_SEARCH_PROVIDER", "fixture")
EVENT_CATALYST_SEARCH_PROVIDERS = tuple(
    _env_csv("RSI_EVENT_CATALYST_SEARCH_PROVIDERS")
    or [EVENT_CATALYST_SEARCH_PROVIDER]
)
EVENT_CATALYST_SEARCH_MAX_ANOMALIES = int(os.getenv("RSI_EVENT_CATALYST_SEARCH_MAX_ANOMALIES", "10"))
EVENT_CATALYST_SEARCH_MAX_QUERIES_PER_ANOMALY = int(os.getenv("RSI_EVENT_CATALYST_SEARCH_MAX_QUERIES_PER_ANOMALY", "6"))
EVENT_CATALYST_SEARCH_MAX_RESULTS_PER_QUERY = int(os.getenv("RSI_EVENT_CATALYST_SEARCH_MAX_RESULTS_PER_QUERY", "5"))
EVENT_CATALYST_SEARCH_MIN_ANOMALY_SCORE = int(os.getenv("RSI_EVENT_CATALYST_SEARCH_MIN_ANOMALY_SCORE", "60"))
EVENT_CATALYST_SEARCH_REQUIRE_LIVE_SOURCE = _env_bool("RSI_EVENT_CATALYST_SEARCH_REQUIRE_LIVE_SOURCE", False)
EVENT_CATALYST_SEARCH_MIN_RESULT_CONFIDENCE = float(os.getenv("RSI_EVENT_CATALYST_SEARCH_MIN_RESULT_CONFIDENCE", "0.50"))
EVENT_IMPACT_HYPOTHESIS_SEARCH_ENABLED = _env_bool("RSI_EVENT_IMPACT_HYPOTHESIS_SEARCH_ENABLED", False)
EVENT_IMPACT_HYPOTHESIS_MAX_HYPOTHESES = int(os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MAX_HYPOTHESES", "10"))
EVENT_IMPACT_HYPOTHESIS_MAX_QUERIES_PER_HYPOTHESIS = int(
    os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MAX_QUERIES_PER_HYPOTHESIS", "4")
)
EVENT_IMPACT_HYPOTHESIS_MIN_CONFIDENCE = float(os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MIN_CONFIDENCE", "0.55"))
EVENT_IMPACT_HYPOTHESIS_MIN_RESULT_CONFIDENCE = float(
    os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MIN_RESULT_CONFIDENCE", "0.50")
)
EVENT_IMPACT_HYPOTHESIS_REQUIRE_VALIDATED_IDENTITY = _env_bool(
    "RSI_EVENT_IMPACT_HYPOTHESIS_REQUIRE_VALIDATED_IDENTITY",
    True,
)
EVENT_IMPACT_HYPOTHESIS_CANDIDATE_DISCOVERY_ENABLED = _env_bool(
    "RSI_EVENT_IMPACT_HYPOTHESIS_CANDIDATE_DISCOVERY_ENABLED",
    False,
)
EVENT_IMPACT_HYPOTHESIS_MAX_DISCOVERY_QUERIES = int(
    os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MAX_DISCOVERY_QUERIES", "10")
)
EVENT_IMPACT_HYPOTHESIS_MAX_DISCOVERY_RESULTS = int(
    os.getenv("RSI_EVENT_IMPACT_HYPOTHESIS_MAX_DISCOVERY_RESULTS", "5")
)
EVENT_ALPHA_EVIDENCE_ACQUISITION_ENABLED = _env_bool("RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_ENABLED", False)
EVENT_ALPHA_EVIDENCE_ACQUISITION_MAX_CANDIDATES = int(
    os.getenv("RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_MAX_CANDIDATES", "10")
)
EVENT_ALPHA_EVIDENCE_ACQUISITION_MAX_QUERIES = int(
    os.getenv("RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_MAX_QUERIES", "20")
)
EVENT_ALPHA_EVIDENCE_ACQUISITION_TIMEOUT_SECONDS = float(
    os.getenv("RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_TIMEOUT_SECONDS", "8")
)
EVENT_ALPHA_EVIDENCE_ACQUISITION_FIXTURE_ONLY = _env_bool(
    "RSI_EVENT_ALPHA_EVIDENCE_ACQUISITION_FIXTURE_ONLY",
    False,
)
EVENT_WATCHLIST_ENABLED = _env_bool("RSI_EVENT_WATCHLIST_ENABLED", False)
EVENT_WATCHLIST_EXPIRE_HOURS_AFTER_EVENT = float(os.getenv("RSI_EVENT_WATCHLIST_EXPIRE_HOURS_AFTER_EVENT", "72"))
EVENT_WATCHLIST_MONITOR_ENABLED = _env_bool("RSI_EVENT_WATCHLIST_MONITOR_ENABLED", False)
EVENT_WATCHLIST_MONITOR_ROUTE_UPDATES = _env_bool("RSI_EVENT_WATCHLIST_MONITOR_ROUTE_UPDATES", True)
EVENT_WATCHLIST_MONITOR_MARKET_SOURCE = os.getenv("RSI_EVENT_WATCHLIST_MONITOR_MARKET_SOURCE", "cycle")
EVENT_WATCHLIST_MONITOR_DERIVATIVES_SOURCE = os.getenv("RSI_EVENT_WATCHLIST_MONITOR_DERIVATIVES_SOURCE", "cycle")
EVENT_WATCHLIST_MONITOR_SUPPLY_SOURCE = os.getenv("RSI_EVENT_WATCHLIST_MONITOR_SUPPLY_SOURCE", "cycle")
EVENT_WATCHLIST_MONITOR_TARGETED_LOOKUP = _env_bool("RSI_EVENT_WATCHLIST_MONITOR_TARGETED_LOOKUP", False)
EVENT_WATCHLIST_MONITOR_MAX_ASSETS = int(os.getenv("RSI_EVENT_WATCHLIST_MONITOR_MAX_ASSETS", "50"))
EVENT_WATCHLIST_MONITOR_ENRICHMENT_MAX_ASSETS = int(
    os.getenv("RSI_EVENT_WATCHLIST_MONITOR_ENRICHMENT_MAX_ASSETS", "50")
)
EVENT_WATCHLIST_MONITOR_MARKET_CACHE_TTL_SECONDS = int(
    os.getenv("RSI_EVENT_WATCHLIST_MONITOR_MARKET_CACHE_TTL_SECONDS", "900")
)
EVENT_ALPHA_APPLY_PRIORS = _env_bool("RSI_EVENT_ALPHA_APPLY_PRIORS", False)
EVENT_ALPHA_PRIORS_MIN_MULTIPLIER = float(os.getenv("RSI_EVENT_ALPHA_PRIORS_MIN_MULTIPLIER", "0.70"))
EVENT_ALPHA_PRIORS_MAX_MULTIPLIER = float(os.getenv("RSI_EVENT_ALPHA_PRIORS_MAX_MULTIPLIER", "1.30"))
EVENT_PROVIDER_MAX_CONSECUTIVE_FAILURES = int(os.getenv("RSI_EVENT_PROVIDER_MAX_CONSECUTIVE_FAILURES", "3"))
EVENT_PROVIDER_BACKOFF_MINUTES = float(os.getenv("RSI_EVENT_PROVIDER_BACKOFF_MINUTES", "30"))
EVENT_PROVIDER_FAIL_FAST_ON_DNS = _env_bool("RSI_EVENT_PROVIDER_FAIL_FAST_ON_DNS", True)
EVENT_ALPHA_IGNORE_PROVIDER_BACKOFF = _env_bool("RSI_EVENT_ALPHA_IGNORE_PROVIDER_BACKOFF", False)
EVENT_ALPHA_RETENTION_DAYS_RUNS = int(os.getenv("RSI_EVENT_ALPHA_RETENTION_DAYS_RUNS", "90"))
EVENT_ALPHA_RETENTION_DAYS_ALERTS = int(os.getenv("RSI_EVENT_ALPHA_RETENTION_DAYS_ALERTS", "180"))
EVENT_ALPHA_RETENTION_DAYS_CARDS = int(os.getenv("RSI_EVENT_ALPHA_RETENTION_DAYS_CARDS", "180"))
EVENT_ALPHA_RETENTION_KEEP_EVAL_CASES = _env_bool("RSI_EVENT_ALPHA_RETENTION_KEEP_EVAL_CASES", True)
EVENT_ALPHA_MAX_RUN_AGE_HOURS = float(os.getenv("RSI_EVENT_ALPHA_MAX_RUN_AGE_HOURS", "6"))
EVENT_ALPHA_MAX_SUCCESS_AGE_HOURS = float(os.getenv("RSI_EVENT_ALPHA_MAX_SUCCESS_AGE_HOURS", "12"))
EVENT_ALPHA_HEALTH_REQUIRE_PROFILE = os.getenv("RSI_EVENT_ALPHA_HEALTH_REQUIRE_PROFILE", "").strip() or None
EVENT_ALPHA_ROUTER_ENABLED = _env_bool("RSI_EVENT_ALPHA_ROUTER_ENABLED", False)
EVENT_ALPHA_ROUTER_DAILY_DIGEST_ENABLED = _env_bool("RSI_EVENT_ALPHA_ROUTER_DAILY_DIGEST_ENABLED", True)
EVENT_ALPHA_ROUTER_INSTANT_ENABLED = _env_bool("RSI_EVENT_ALPHA_ROUTER_INSTANT_ENABLED", True)
EVENT_ALPHA_ROUTER_MAX_DIGEST_ITEMS = int(os.getenv("RSI_EVENT_ALPHA_ROUTER_MAX_DIGEST_ITEMS", "20"))
EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_ENABLED = _env_bool(
    "RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_ENABLED",
    False,
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_MAX_ITEMS = int(
    os.getenv("RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_MAX_ITEMS", "5")
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_MAX_ITEMS = int(
    os.getenv(
        "RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_MAX_ITEMS",
        str(EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_MAX_ITEMS),
    )
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_MIN_SCORE = float(
    os.getenv("RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_DIGEST_MIN_SCORE", "65")
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_MIN_OPPORTUNITY_SCORE = float(
    os.getenv("RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_MIN_OPPORTUNITY_SCORE", "65")
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_MIN_FINAL_SCORE = float(
    os.getenv("RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_MIN_FINAL_SCORE", "65")
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_REQUIRE_EXTERNAL_OR_DIRECT_EVENT = _env_bool(
    "RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_REQUIRE_EXTERNAL_OR_DIRECT_EVENT",
    True,
)
EVENT_ALPHA_VALIDATED_HYPOTHESIS_REQUIRE_IMPACT_PATH = _env_bool(
    "RSI_EVENT_ALPHA_VALIDATED_HYPOTHESIS_REQUIRE_IMPACT_PATH",
    True,
)
EVENT_ALPHA_WEAK_VALIDATED_LOCAL_ONLY = _env_bool(
    "RSI_EVENT_ALPHA_WEAK_VALIDATED_LOCAL_ONLY",
    True,
)
EVENT_ALPHA_ALLOW_WEAK_PATH_WITH_MARKET_CONFIRMATION = _env_bool(
    "RSI_EVENT_ALPHA_ALLOW_WEAK_PATH_WITH_MARKET_CONFIRMATION",
    True,
)
EVENT_ALPHA_BLOCK_GENERIC_COOCCURRENCE_DIGEST = _env_bool(
    "RSI_EVENT_ALPHA_BLOCK_GENERIC_COOCCURRENCE_DIGEST",
    True,
)
EVENT_ALPHA_ALLOW_SECTOR_DIGEST = _env_bool("RSI_EVENT_ALPHA_ALLOW_SECTOR_DIGEST", False)
EVENT_ALPHA_ALLOW_MAJOR_PAIR_CATALYSTS = _env_bool("RSI_EVENT_ALPHA_ALLOW_MAJOR_PAIR_CATALYSTS", False)
_TARGETED_MARKET_REFRESH_ENABLED = _env_bool("RSI_EVENT_ALPHA_TARGETED_MARKET_REFRESH_ENABLED", False)
EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_ENABLED = _env_bool(
    "RSI_EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_ENABLED",
    _TARGETED_MARKET_REFRESH_ENABLED,
)
EVENT_ALPHA_TARGETED_MARKET_REFRESH_ENABLED = EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_ENABLED
EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_MAX_ASSETS = int(
    os.getenv(
        "RSI_EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_MAX_ASSETS",
        os.getenv("RSI_EVENT_ALPHA_TARGETED_MARKET_REFRESH_MAX_ASSETS", "20"),
    )
)
EVENT_ALPHA_TARGETED_MARKET_REFRESH_MAX_ASSETS = EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_MAX_ASSETS
EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_TIMEOUT_SECONDS = float(
    os.getenv(
        "RSI_EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_TIMEOUT_SECONDS",
        os.getenv("RSI_EVENT_ALPHA_TARGETED_MARKET_REFRESH_TIMEOUT_SECONDS", "5"),
    )
)
EVENT_ALPHA_TARGETED_MARKET_REFRESH_TIMEOUT_SECONDS = EVENT_ALPHA_NEAR_MISS_MARKET_REFRESH_TIMEOUT_SECONDS
EVENT_ALPHA_TARGETED_MARKET_REFRESH_PROFILE_ALLOW_FIXTURE = _env_bool(
    "RSI_EVENT_ALPHA_TARGETED_MARKET_REFRESH_PROFILE_ALLOW_FIXTURE",
    False,
)
EVENT_ALPHA_NEAR_MISS_THRESHOLD_POINTS = float(
    os.getenv("RSI_EVENT_ALPHA_NEAR_MISS_THRESHOLD_POINTS", "10")
)
EVENT_ALPHA_ROUTER_MAX_HIGH_PRIORITY_PER_DAY = int(os.getenv("RSI_EVENT_ALPHA_ROUTER_MAX_HIGH_PRIORITY_PER_DAY", "3"))
EVENT_ALPHA_ROUTER_PER_KEY_COOLDOWN_HOURS = float(os.getenv("RSI_EVENT_ALPHA_ROUTER_PER_KEY_COOLDOWN_HOURS", "12"))
EVENT_ALPHA_ROUTER_ALERT_ON_SCORE_JUMP = _env_bool("RSI_EVENT_ALPHA_ROUTER_ALERT_ON_SCORE_JUMP", True)
EVENT_ALPHA_ROUTER_SCORE_JUMP_THRESHOLD = int(os.getenv("RSI_EVENT_ALPHA_ROUTER_SCORE_JUMP_THRESHOLD", "10"))
EVENT_ALPHA_ROUTER_ALERT_ON_NEW_INDEPENDENT_SOURCE = _env_bool("RSI_EVENT_ALPHA_ROUTER_ALERT_ON_NEW_INDEPENDENT_SOURCE", True)
EVENT_ALPHA_ROUTER_ALERT_ON_EVENT_TIME_UPGRADE = _env_bool("RSI_EVENT_ALPHA_ROUTER_ALERT_ON_EVENT_TIME_UPGRADE", True)
EVENT_ALPHA_ROUTER_ALERT_ON_DERIVATIVES_CROWDING_UPGRADE = _env_bool("RSI_EVENT_ALPHA_ROUTER_ALERT_ON_DERIVATIVES_CROWDING_UPGRADE", True)
EVENT_ALPHA_ROUTER_ALERT_ON_CLUSTER_CONFIDENCE_UPGRADE = _env_bool("RSI_EVENT_ALPHA_ROUTER_ALERT_ON_CLUSTER_CONFIDENCE_UPGRADE", True)
EVENT_ALPHA_NOTIFY_DAILY_DIGEST_COOLDOWN_HOURS = float(
    os.getenv("RSI_EVENT_ALPHA_NOTIFY_DAILY_DIGEST_COOLDOWN_HOURS", str(EVENT_ALERT_COOLDOWN_HOURS))
)
EVENT_ALPHA_NOTIFY_SCOPE = os.getenv("RSI_EVENT_ALPHA_NOTIFY_SCOPE", "global").strip().lower() or "global"
EVENT_ALPHA_NOTIFY_INSTANT_COOLDOWN_HOURS = float(
    os.getenv("RSI_EVENT_ALPHA_NOTIFY_INSTANT_COOLDOWN_HOURS", "1")
)
EVENT_ALPHA_NOTIFY_MAX_INSTANT_PER_DAY = int(
    os.getenv("RSI_EVENT_ALPHA_NOTIFY_MAX_INSTANT_PER_DAY", str(EVENT_ALERT_MAX_INSTANT_PER_DAY))
)
EVENT_ALPHA_NOTIFY_HEALTH_HEARTBEAT_ENABLED = _env_bool("RSI_EVENT_ALPHA_NOTIFY_HEALTH_HEARTBEAT_ENABLED", True)
EVENT_ALPHA_NOTIFY_HEALTH_HEARTBEAT_COOLDOWN_HOURS = float(
    os.getenv("RSI_EVENT_ALPHA_NOTIFY_HEALTH_HEARTBEAT_COOLDOWN_HOURS", "24")
)
EVENT_ALPHA_EXPLORATORY_DIGEST_ENABLED = _env_bool("RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_ENABLED", False)
EVENT_ALPHA_EXPLORATORY_DIGEST_MAX_ITEMS = int(os.getenv("RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_MAX_ITEMS", "10"))
EVENT_ALPHA_EXPLORATORY_DIGEST_MIN_SCORE = int(os.getenv("RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_MIN_SCORE", "0"))
EVENT_ALPHA_EXPLORATORY_DIGEST_COOLDOWN_HOURS = float(
    os.getenv("RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_COOLDOWN_HOURS", "24")
)
EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_REJECTION_REASONS = _env_bool(
    "RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_REJECTION_REASONS",
    True,
)
EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_RAW_EVIDENCE = _env_bool(
    "RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_RAW_EVIDENCE",
    True,
)
EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_CONTROLS = _env_bool(
    "RSI_EVENT_ALPHA_EXPLORATORY_DIGEST_INCLUDE_CONTROLS",
    False,
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_ENABLED = _env_bool(
    "RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_ENABLED",
    False,
)
EVENT_ALPHA_DAILY_DIGEST_MAX_ITEMS = int(os.getenv("RSI_EVENT_ALPHA_DAILY_DIGEST_MAX_ITEMS", "5"))
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_MAX_ITEMS = int(
    os.getenv("RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_MAX_ITEMS", "3")
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_MIN_SCORE = float(
    os.getenv("RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_MIN_SCORE", "60")
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_COOLDOWN_HOURS = float(
    os.getenv("RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_COOLDOWN_HOURS", "12")
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_INCLUDE_LOCAL_ONLY = _env_bool(
    "RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_INCLUDE_LOCAL_ONLY",
    False,
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_INCLUDE_SECTOR = _env_bool(
    "RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_INCLUDE_SECTOR",
    False,
)
EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_SEND_WITH_ALERTS = _env_bool(
    "RSI_EVENT_ALPHA_RESEARCH_REVIEW_DIGEST_SEND_WITH_ALERTS",
    False,
)
EVENT_ALPHA_ALLOW_SOURCE_ONLY_NARRATIVE_DIGEST = _env_bool(
    "RSI_EVENT_ALPHA_ALLOW_SOURCE_ONLY_NARRATIVE_DIGEST",
    False,
)
EVENT_ALPHA_NOTIFICATION_QUALITY_MODE = (
    os.getenv("RSI_EVENT_ALPHA_NOTIFICATION_QUALITY_MODE", "validated_digest").strip().lower()
    or "validated_digest"
)
EVENT_ALPHA_NOTIFY_MAX_RUNTIME_SECONDS = float(os.getenv("RSI_EVENT_ALPHA_NOTIFY_MAX_RUNTIME_SECONDS", "120"))
EVENT_ALPHA_NOTIFY_PROVIDER_TIMEOUT_SECONDS = float(os.getenv("RSI_EVENT_ALPHA_NOTIFY_PROVIDER_TIMEOUT_SECONDS", "5"))
EVENT_ALPHA_NOTIFY_MAX_PROVIDER_FAILURES_BEFORE_SKIP = int(
    os.getenv("RSI_EVENT_ALPHA_NOTIFY_MAX_PROVIDER_FAILURES_BEFORE_SKIP", "1")
)
EVENT_ALPHA_NOTIFY_FAST_FAIL_ON_DNS = _env_bool("RSI_EVENT_ALPHA_NOTIFY_FAST_FAIL_ON_DNS", True)
EVENT_ALPHA_NOTIFY_ALLOW_PARTIAL_RESULTS = _env_bool("RSI_EVENT_ALPHA_NOTIFY_ALLOW_PARTIAL_RESULTS", True)
EVENT_ALPHA_ALLOW_FIXED_NOW_FOR_NOTIFY = _env_bool("RSI_EVENT_ALPHA_ALLOW_FIXED_NOW_FOR_NOTIFY", False)
EVENT_ALPHA_NOTIFICATIONS_PAUSED = _env_bool("RSI_EVENT_ALPHA_NOTIFICATIONS_PAUSED", False)
EVENT_ALPHA_NOTIFICATIONS_PAUSE_REASON = os.getenv("RSI_EVENT_ALPHA_NOTIFICATIONS_PAUSE_REASON", "").strip()
# Per-profile notification run lock: prevents overlapping scheduled notify cycles
# from double-sending or racing on lane cooldown state. Research-only.
EVENT_ALPHA_NOTIFY_LOCK_ENABLED = _env_bool("RSI_EVENT_ALPHA_NOTIFY_LOCK_ENABLED", True)
EVENT_ALPHA_NOTIFY_LOCK_STALE_MINUTES = float(os.getenv("RSI_EVENT_ALPHA_NOTIFY_LOCK_STALE_MINUTES", "30"))
EVENT_ALPHA_NOTIFY_ALLOW_OVERLAP = _env_bool("RSI_EVENT_ALPHA_NOTIFY_ALLOW_OVERLAP", False)
# Idempotent notification delivery ledger: dedupes identical research digests
# within a window and records delivered/failed/skipped outcomes. Research-only.
# Path defaults to <namespace>/event_alpha_notification_deliveries.jsonl;
# RSI_EVENT_ALPHA_NOTIFICATION_DELIVERIES_PATH overrides it (read where used).
EVENT_ALPHA_NOTIFICATION_DEDUPE_BY_CONTENT = _env_bool("RSI_EVENT_ALPHA_NOTIFICATION_DEDUPE_BY_CONTENT", True)
EVENT_ALPHA_NOTIFICATION_DEDUPE_WINDOW_HOURS = float(os.getenv("RSI_EVENT_ALPHA_NOTIFICATION_DEDUPE_WINDOW_HOURS", "24"))
EVENT_ALPHA_NOTIFICATION_IN_FLIGHT_GRACE_MINUTES = float(
    os.getenv("RSI_EVENT_ALPHA_NOTIFICATION_IN_FLIGHT_GRACE_MINUTES", "10")
)
EVENT_ALPHA_NOTIFICATION_PARTIAL_MARKS_COOLDOWN = _env_bool(
    "RSI_EVENT_ALPHA_NOTIFICATION_PARTIAL_MARKS_COOLDOWN",
    True,
)
EVENT_RESEARCH_CARDS_AUTO_WRITE = _env_bool("RSI_EVENT_RESEARCH_CARDS_AUTO_WRITE", False)
EVENT_RESEARCH_CARDS_WRITE_TIERS = tuple(
    _env_csv("RSI_EVENT_RESEARCH_CARDS_WRITE_TIERS")
    or ["HIGH_PRIORITY_WATCH", "TRIGGERED_FADE", "WATCHLIST"]
)
EVENT_RESEARCH_CARDS_WRITE_LIMIT = int(os.getenv("RSI_EVENT_RESEARCH_CARDS_WRITE_LIMIT", "250"))

# Macro context header in the digest (Fear & Greed + BTC trend + breadth).
MACRO_ENABLED = (os.getenv("RSI_MACRO", "1").lower() not in ("0", "false", "no"))

# Heartbeat / dead-man's-switch: alert if a run breaks or degrades silently.
HEARTBEAT_ENABLED = (os.getenv("RSI_HEARTBEAT", "1").lower() not in ("0", "false", "no"))
# Warn if more than this fraction of coins fail to fetch (silent degradation).
HEARTBEAT_MAX_FETCH_FAIL_RATIO = float(os.getenv("RSI_HEARTBEAT_MAX_FAIL", "0.30"))

# Stale-scan watchdog: the always-on listener alerts (once) if no successful scan
# has landed in STALE_SCAN_HOURS — catches a Mac asleep through the 03:10 schedule,
# an unloaded launchd job, or a silently-failing scan. Default 36h tolerates normal
# overnight sleep; lower it for a tighter watch. Gated by HEARTBEAT_ENABLED.
STALE_SCAN_HOURS = float(os.getenv("RSI_STALE_SCAN_HOURS", "36"))
STALE_CHECK_INTERVAL_SEC = int(os.getenv("RSI_STALE_CHECK_INTERVAL_SEC", "1800"))

RSI_4H_FETCH_UPPER = 60.0
RSI_4H_FETCH_LOWER = 40.0

# Universe hygiene. The live scan/backtest request a larger CoinGecko candidate
# pool, then filter stablecoins, wrapped/staked receipts, stale/suspicious
# listings, and illiquid assets before taking the requested top-N.
UNIVERSE_FETCH_MULTIPLIER = int(os.getenv("RSI_UNIVERSE_FETCH_MULTIPLIER", "2"))
UNIVERSE_EXTRA_CANDIDATES = int(os.getenv("RSI_UNIVERSE_EXTRA_CANDIDATES", "50"))
UNIVERSE_MAX_CANDIDATES = int(os.getenv("RSI_UNIVERSE_MAX_CANDIDATES", "250"))
UNIVERSE_MIN_VOLUME_TO_MCAP = float(os.getenv("RSI_MIN_VOLUME_TO_MCAP", "0.001"))
UNIVERSE_MIN_MARKET_CAP_USD = float(os.getenv("RSI_MIN_MARKET_CAP_USD", "0"))
UNIVERSE_MAX_ABS_24H_CHANGE = float(os.getenv("RSI_MAX_ABS_24H_CHANGE", "500"))

EXCLUDE_SYMBOLS = {
    "usdt", "usdc", "dai", "usde", "fdusd", "tusd", "usdd", "pyusd", "usds",
    "busd", "gusd", "frax", "lusd", "usd0", "usdb", "crvusd", "usdx",
    "usd1", "usdg", "usdtb", "gho", "ylds", "usx", "usyc", "xaut", "paxg",
    "wbtc", "weth", "weeth", "wsteth", "steth", "reth", "cbbtc", "cbeth",
    "solvbtc", "lbtc", "wbeth", "meth", "ezeth", "rseth", "bnsol", "jitosol",
    "wbnb",
}

COINGECKO_API_KEY = os.getenv("COINGECKO_API_KEY")
COINGECKO_KEY_TYPE = (os.getenv("COINGECKO_KEY_TYPE") or "demo").lower()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
# One or more recipient chat IDs, comma-separated (e.g. "133428954,987654321").
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
TELEGRAM_CHAT_IDS = [
    cid.strip() for cid in (TELEGRAM_CHAT_ID or "").split(",") if cid.strip()
]
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")

DATA_DIR = Path(__file__).resolve().parent.parent
DB_PATH = DATA_DIR / "rsi_scanner.db"
CSV_OUT = DATA_DIR / "rsi_scan_latest.csv"

if not EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH.is_absolute():
    EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH = DATA_DIR / EVENT_ALPHA_MARKET_ANOMALY_ROWS_PATH
if not EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH.is_absolute():
    EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH = DATA_DIR / EVENT_ALPHA_OFFICIAL_EXCHANGE_BINANCE_PATH
if not EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH.is_absolute():
    EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH = DATA_DIR / EVENT_ALPHA_OFFICIAL_EXCHANGE_BYBIT_PATH
if not EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH.is_absolute():
    EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH = DATA_DIR / EVENT_ALPHA_SCHEDULED_CATALYST_TOKENOMIST_PATH
if not EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH.is_absolute():
    EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH = DATA_DIR / EVENT_ALPHA_SCHEDULED_CATALYST_MESSARI_PATH
if not EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH.is_absolute():
    EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH = DATA_DIR / EVENT_ALPHA_SCHEDULED_CATALYST_COINMARKETCAL_PATH
if not EVENT_ALPHA_DERIVATIVES_CROWDING_PATH.is_absolute():
    EVENT_ALPHA_DERIVATIVES_CROWDING_PATH = DATA_DIR / EVENT_ALPHA_DERIVATIVES_CROWDING_PATH

EVENT_FADE_EVENTS_PATH = Path(_EVENT_FADE_EVENTS_PATH_RAW).expanduser() if _EVENT_FADE_EVENTS_PATH_RAW else None
if EVENT_FADE_EVENTS_PATH is not None and not EVENT_FADE_EVENTS_PATH.is_absolute():
    EVENT_FADE_EVENTS_PATH = DATA_DIR / EVENT_FADE_EVENTS_PATH

EVENT_DISCOVERY_EVENTS_PATH = (
    Path(_EVENT_DISCOVERY_EVENTS_PATH_RAW).expanduser() if _EVENT_DISCOVERY_EVENTS_PATH_RAW else None
)
if EVENT_DISCOVERY_EVENTS_PATH is not None and not EVENT_DISCOVERY_EVENTS_PATH.is_absolute():
    EVENT_DISCOVERY_EVENTS_PATH = DATA_DIR / EVENT_DISCOVERY_EVENTS_PATH
EVENT_DISCOVERY_ALIASES_PATH = Path(_EVENT_DISCOVERY_ALIASES_PATH_RAW).expanduser()
if not EVENT_DISCOVERY_ALIASES_PATH.is_absolute():
    EVENT_DISCOVERY_ALIASES_PATH = DATA_DIR / EVENT_DISCOVERY_ALIASES_PATH
EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH = (
    Path(_EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH is not None
    and not EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH.is_absolute()
):
    EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH = DATA_DIR / EVENT_DISCOVERY_BINANCE_ANNOUNCEMENTS_PATH
EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH = (
    Path(_EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH is not None
    and not EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH.is_absolute()
):
    EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH = DATA_DIR / EVENT_DISCOVERY_BYBIT_ANNOUNCEMENTS_PATH
EVENT_DISCOVERY_COINMARKETCAL_PATH = (
    Path(_EVENT_DISCOVERY_COINMARKETCAL_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_COINMARKETCAL_PATH_RAW
    else None
)
if EVENT_DISCOVERY_COINMARKETCAL_PATH is not None and not EVENT_DISCOVERY_COINMARKETCAL_PATH.is_absolute():
    EVENT_DISCOVERY_COINMARKETCAL_PATH = DATA_DIR / EVENT_DISCOVERY_COINMARKETCAL_PATH
EVENT_DISCOVERY_TOKENOMIST_PATH = (
    Path(_EVENT_DISCOVERY_TOKENOMIST_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_TOKENOMIST_PATH_RAW
    else None
)
if EVENT_DISCOVERY_TOKENOMIST_PATH is not None and not EVENT_DISCOVERY_TOKENOMIST_PATH.is_absolute():
    EVENT_DISCOVERY_TOKENOMIST_PATH = DATA_DIR / EVENT_DISCOVERY_TOKENOMIST_PATH
EVENT_DISCOVERY_CRYPTOPANIC_PATH = (
    Path(_EVENT_DISCOVERY_CRYPTOPANIC_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_CRYPTOPANIC_PATH_RAW
    else None
)
if EVENT_DISCOVERY_CRYPTOPANIC_PATH is not None and not EVENT_DISCOVERY_CRYPTOPANIC_PATH.is_absolute():
    EVENT_DISCOVERY_CRYPTOPANIC_PATH = DATA_DIR / EVENT_DISCOVERY_CRYPTOPANIC_PATH
EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH = (
    Path(_EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH_RAW
    else Path(_EVENT_DISCOVERY_CACHE_DIR_RAW).expanduser() / "cryptopanic_request_ledger.jsonl"
)
if not EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH.is_absolute():
    EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH = DATA_DIR / EVENT_DISCOVERY_CRYPTOPANIC_REQUEST_LEDGER_PATH
EVENT_DISCOVERY_GDELT_PATH = (
    Path(_EVENT_DISCOVERY_GDELT_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_GDELT_PATH_RAW
    else None
)
if EVENT_DISCOVERY_GDELT_PATH is not None and not EVENT_DISCOVERY_GDELT_PATH.is_absolute():
    EVENT_DISCOVERY_GDELT_PATH = DATA_DIR / EVENT_DISCOVERY_GDELT_PATH
EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH = (
    Path(_EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH is not None
    and not EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH.is_absolute()
):
    EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH = DATA_DIR / EVENT_DISCOVERY_PROJECT_BLOG_RSS_PATH
EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH = (
    Path(_EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH is not None
    and not EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH.is_absolute()
):
    EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH = DATA_DIR / EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH
EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS = _merge_csv_and_file_urls(
    _EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS,
    _load_url_list(EVENT_DISCOVERY_PROJECT_BLOG_RSS_URLS_PATH),
)
EVENT_DISCOVERY_EXTERNAL_IPO_PATH = (
    Path(_EVENT_DISCOVERY_EXTERNAL_IPO_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_EXTERNAL_IPO_PATH_RAW
    else None
)
if EVENT_DISCOVERY_EXTERNAL_IPO_PATH is not None and not EVENT_DISCOVERY_EXTERNAL_IPO_PATH.is_absolute():
    EVENT_DISCOVERY_EXTERNAL_IPO_PATH = DATA_DIR / EVENT_DISCOVERY_EXTERNAL_IPO_PATH
EVENT_DISCOVERY_SPORTS_FIXTURES_PATH = (
    Path(_EVENT_DISCOVERY_SPORTS_FIXTURES_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_SPORTS_FIXTURES_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_SPORTS_FIXTURES_PATH is not None
    and not EVENT_DISCOVERY_SPORTS_FIXTURES_PATH.is_absolute()
):
    EVENT_DISCOVERY_SPORTS_FIXTURES_PATH = DATA_DIR / EVENT_DISCOVERY_SPORTS_FIXTURES_PATH
EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH = (
    Path(_EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH is not None
    and not EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH.is_absolute()
):
    EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH = DATA_DIR / EVENT_DISCOVERY_PREDICTION_MARKET_EVENTS_PATH
EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH = (
    Path(_EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH is not None
    and not EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH.is_absolute()
):
    EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH = DATA_DIR / EVENT_DISCOVERY_COINALYZE_DERIVATIVES_PATH
EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH = (
    Path(_EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH is not None
    and not EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH.is_absolute()
):
    EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH = DATA_DIR / EVENT_DISCOVERY_TOKENOMIST_SUPPLY_PATH
EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH = (
    Path(_EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH_RAW
    else None
)
if (
    EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH is not None
    and not EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH.is_absolute()
):
    EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH = DATA_DIR / EVENT_DISCOVERY_ETHERSCAN_SUPPLY_PATH
EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH = (
    Path(_EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH_RAW
    else None
)
if EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH is not None and not EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH.is_absolute():
    EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH = DATA_DIR / EVENT_DISCOVERY_ARKHAM_SUPPLY_PATH
EVENT_DISCOVERY_DUNE_SUPPLY_PATH = (
    Path(_EVENT_DISCOVERY_DUNE_SUPPLY_PATH_RAW).expanduser()
    if _EVENT_DISCOVERY_DUNE_SUPPLY_PATH_RAW
    else None
)
if EVENT_DISCOVERY_DUNE_SUPPLY_PATH is not None and not EVENT_DISCOVERY_DUNE_SUPPLY_PATH.is_absolute():
    EVENT_DISCOVERY_DUNE_SUPPLY_PATH = DATA_DIR / EVENT_DISCOVERY_DUNE_SUPPLY_PATH
EVENT_DISCOVERY_UNIVERSE_PATH = (
    Path(_EVENT_DISCOVERY_UNIVERSE_PATH_RAW).expanduser() if _EVENT_DISCOVERY_UNIVERSE_PATH_RAW else None
)
if EVENT_DISCOVERY_UNIVERSE_PATH is not None and not EVENT_DISCOVERY_UNIVERSE_PATH.is_absolute():
    EVENT_DISCOVERY_UNIVERSE_PATH = DATA_DIR / EVENT_DISCOVERY_UNIVERSE_PATH
EVENT_ASSET_REGISTRY_PATH = (
    Path(_EVENT_ASSET_REGISTRY_PATH_RAW).expanduser() if _EVENT_ASSET_REGISTRY_PATH_RAW else None
)
if EVENT_ASSET_REGISTRY_PATH is not None and not EVENT_ASSET_REGISTRY_PATH.is_absolute():
    EVENT_ASSET_REGISTRY_PATH = DATA_DIR / EVENT_ASSET_REGISTRY_PATH
EVENT_DISCOVERY_CACHE_DIR = Path(_EVENT_DISCOVERY_CACHE_DIR_RAW).expanduser()
if not EVENT_DISCOVERY_CACHE_DIR.is_absolute():
    EVENT_DISCOVERY_CACHE_DIR = DATA_DIR / EVENT_DISCOVERY_CACHE_DIR
EVENT_ALPHA_ARTIFACT_BASE_DIR = (
    Path(_EVENT_ALPHA_ARTIFACT_BASE_DIR_RAW).expanduser()
    if _EVENT_ALPHA_ARTIFACT_BASE_DIR_RAW
    else EVENT_DISCOVERY_CACHE_DIR
)
if not EVENT_ALPHA_ARTIFACT_BASE_DIR.is_absolute():
    EVENT_ALPHA_ARTIFACT_BASE_DIR = DATA_DIR / EVENT_ALPHA_ARTIFACT_BASE_DIR
EVENT_WATCHLIST_STATE_PATH = (
    Path(_EVENT_WATCHLIST_STATE_PATH_RAW).expanduser()
    if _EVENT_WATCHLIST_STATE_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_watchlist_state.jsonl"
)
if not EVENT_WATCHLIST_STATE_PATH.is_absolute():
    EVENT_WATCHLIST_STATE_PATH = DATA_DIR / EVENT_WATCHLIST_STATE_PATH
EVENT_WATCHLIST_MONITOR_MARKET_PATH = (
    Path(_EVENT_WATCHLIST_MONITOR_MARKET_PATH_RAW).expanduser()
    if _EVENT_WATCHLIST_MONITOR_MARKET_PATH_RAW
    else None
)
if EVENT_WATCHLIST_MONITOR_MARKET_PATH is not None and not EVENT_WATCHLIST_MONITOR_MARKET_PATH.is_absolute():
    EVENT_WATCHLIST_MONITOR_MARKET_PATH = DATA_DIR / EVENT_WATCHLIST_MONITOR_MARKET_PATH
EVENT_ALPHA_FEEDBACK_PATH = (
    Path(_EVENT_ALPHA_FEEDBACK_PATH_RAW).expanduser()
    if _EVENT_ALPHA_FEEDBACK_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_feedback.jsonl"
)
if not EVENT_ALPHA_FEEDBACK_PATH.is_absolute():
    EVENT_ALPHA_FEEDBACK_PATH = DATA_DIR / EVENT_ALPHA_FEEDBACK_PATH
EVENT_ALPHA_ALERT_STORE_PATH = (
    Path(_EVENT_ALPHA_ALERT_STORE_PATH_RAW).expanduser()
    if _EVENT_ALPHA_ALERT_STORE_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_alerts.jsonl"
)
if not EVENT_ALPHA_ALERT_STORE_PATH.is_absolute():
    EVENT_ALPHA_ALERT_STORE_PATH = DATA_DIR / EVENT_ALPHA_ALERT_STORE_PATH
EVENT_ALPHA_NOTIFICATION_RUNS_PATH = (
    Path(_EVENT_ALPHA_NOTIFICATION_RUNS_PATH_RAW).expanduser()
    if _EVENT_ALPHA_NOTIFICATION_RUNS_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_notification_runs.jsonl"
)
if not EVENT_ALPHA_NOTIFICATION_RUNS_PATH.is_absolute():
    EVENT_ALPHA_NOTIFICATION_RUNS_PATH = DATA_DIR / EVENT_ALPHA_NOTIFICATION_RUNS_PATH
EVENT_ALPHA_RUN_LEDGER_PATH = (
    Path(_EVENT_ALPHA_RUN_LEDGER_PATH_RAW).expanduser()
    if _EVENT_ALPHA_RUN_LEDGER_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_runs.jsonl"
)
if not EVENT_ALPHA_RUN_LEDGER_PATH.is_absolute():
    EVENT_ALPHA_RUN_LEDGER_PATH = DATA_DIR / EVENT_ALPHA_RUN_LEDGER_PATH
EVENT_ALPHA_MISSED_PATH = (
    Path(_EVENT_ALPHA_MISSED_PATH_RAW).expanduser()
    if _EVENT_ALPHA_MISSED_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_missed.jsonl"
)
if not EVENT_ALPHA_MISSED_PATH.is_absolute():
    EVENT_ALPHA_MISSED_PATH = DATA_DIR / EVENT_ALPHA_MISSED_PATH
EVENT_ALPHA_PRIORS_PATH = (
    Path(_EVENT_ALPHA_PRIORS_PATH_RAW).expanduser()
    if _EVENT_ALPHA_PRIORS_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_priors.json"
)
if not EVENT_ALPHA_PRIORS_PATH.is_absolute():
    EVENT_ALPHA_PRIORS_PATH = DATA_DIR / EVENT_ALPHA_PRIORS_PATH
EVENT_ALPHA_OUTCOMES_PATH = (
    Path(_EVENT_ALPHA_OUTCOMES_PATH_RAW).expanduser()
    if _EVENT_ALPHA_OUTCOMES_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_outcomes.jsonl"
)
if not EVENT_ALPHA_OUTCOMES_PATH.is_absolute():
    EVENT_ALPHA_OUTCOMES_PATH = DATA_DIR / EVENT_ALPHA_OUTCOMES_PATH
EVENT_PROVIDER_HEALTH_PATH = (
    Path(_EVENT_PROVIDER_HEALTH_PATH_RAW).expanduser()
    if _EVENT_PROVIDER_HEALTH_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_provider_health.json"
)
if not EVENT_PROVIDER_HEALTH_PATH.is_absolute():
    EVENT_PROVIDER_HEALTH_PATH = DATA_DIR / EVENT_PROVIDER_HEALTH_PATH
EVENT_ALPHA_DAILY_BRIEF_PATH = (
    Path(_EVENT_ALPHA_DAILY_BRIEF_PATH_RAW).expanduser()
    if _EVENT_ALPHA_DAILY_BRIEF_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_alpha_daily_brief.md"
)
if not EVENT_ALPHA_DAILY_BRIEF_PATH.is_absolute():
    EVENT_ALPHA_DAILY_BRIEF_PATH = DATA_DIR / EVENT_ALPHA_DAILY_BRIEF_PATH
EVENT_IMPACT_HYPOTHESIS_STORE_PATH = (
    Path(_EVENT_IMPACT_HYPOTHESIS_STORE_PATH_RAW).expanduser()
    if _EVENT_IMPACT_HYPOTHESIS_STORE_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_impact_hypotheses.jsonl"
)
if not EVENT_IMPACT_HYPOTHESIS_STORE_PATH.is_absolute():
    EVENT_IMPACT_HYPOTHESIS_STORE_PATH = DATA_DIR / EVENT_IMPACT_HYPOTHESIS_STORE_PATH
EVENT_CORE_OPPORTUNITY_STORE_PATH = (
    Path(_EVENT_CORE_OPPORTUNITY_STORE_PATH_RAW).expanduser()
    if _EVENT_CORE_OPPORTUNITY_STORE_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_core_opportunities.jsonl"
)
if not EVENT_CORE_OPPORTUNITY_STORE_PATH.is_absolute():
    EVENT_CORE_OPPORTUNITY_STORE_PATH = DATA_DIR / EVENT_CORE_OPPORTUNITY_STORE_PATH
EVENT_INCIDENT_STORE_PATH = (
    Path(_EVENT_INCIDENT_STORE_PATH_RAW).expanduser()
    if _EVENT_INCIDENT_STORE_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_incidents.jsonl"
)
if not EVENT_INCIDENT_STORE_PATH.is_absolute():
    EVENT_INCIDENT_STORE_PATH = DATA_DIR / EVENT_INCIDENT_STORE_PATH
EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH = (
    Path(_EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH_RAW).expanduser()
    if _EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_evidence_acquisition.jsonl"
)
if not EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH.is_absolute():
    EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH = DATA_DIR / EVENT_ALPHA_EVIDENCE_ACQUISITION_PATH
EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR = (
    Path(_EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR_RAW).expanduser()
    if _EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "proposed_eval_cases"
)
if not EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR.is_absolute():
    EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR = DATA_DIR / EVENT_ALPHA_PROPOSED_EVAL_CASES_DIR
EVENT_RESEARCH_CARDS_DIR = (
    Path(_EVENT_RESEARCH_CARDS_DIR_RAW).expanduser()
    if _EVENT_RESEARCH_CARDS_DIR_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "research_cards"
)
if not EVENT_RESEARCH_CARDS_DIR.is_absolute():
    EVENT_RESEARCH_CARDS_DIR = DATA_DIR / EVENT_RESEARCH_CARDS_DIR
EVENT_CATALYST_SEARCH_FIXTURE_PATH = (
    Path(_EVENT_CATALYST_SEARCH_FIXTURE_PATH_RAW).expanduser()
    if _EVENT_CATALYST_SEARCH_FIXTURE_PATH_RAW
    else None
)
if EVENT_CATALYST_SEARCH_FIXTURE_PATH is not None and not EVENT_CATALYST_SEARCH_FIXTURE_PATH.is_absolute():
    EVENT_CATALYST_SEARCH_FIXTURE_PATH = DATA_DIR / EVENT_CATALYST_SEARCH_FIXTURE_PATH
EVENT_IMPACT_TAXONOMY_PATH = Path(_EVENT_IMPACT_TAXONOMY_PATH_RAW).expanduser()
if not EVENT_IMPACT_TAXONOMY_PATH.is_absolute():
    EVENT_IMPACT_TAXONOMY_PATH = DATA_DIR / EVENT_IMPACT_TAXONOMY_PATH
EVENT_SOURCE_ENRICHMENT_CACHE_DIR = (
    Path(_EVENT_SOURCE_ENRICHMENT_CACHE_DIR_RAW).expanduser()
    if _EVENT_SOURCE_ENRICHMENT_CACHE_DIR_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "source_enrichment"
)
if not EVENT_SOURCE_ENRICHMENT_CACHE_DIR.is_absolute():
    EVENT_SOURCE_ENRICHMENT_CACHE_DIR = DATA_DIR / EVENT_SOURCE_ENRICHMENT_CACHE_DIR
EVENT_LLM_CACHE_PATH = Path(_EVENT_LLM_CACHE_PATH_RAW).expanduser() if _EVENT_LLM_CACHE_PATH_RAW else None
if EVENT_LLM_CACHE_PATH is not None and not EVENT_LLM_CACHE_PATH.is_absolute():
    EVENT_LLM_CACHE_PATH = DATA_DIR / EVENT_LLM_CACHE_PATH
EVENT_LLM_BUDGET_LEDGER_PATH = (
    Path(_EVENT_LLM_BUDGET_LEDGER_PATH_RAW).expanduser()
    if _EVENT_LLM_BUDGET_LEDGER_PATH_RAW
    else EVENT_DISCOVERY_CACHE_DIR / "event_llm_budget.json"
)
if not EVENT_LLM_BUDGET_LEDGER_PATH.is_absolute():
    EVENT_LLM_BUDGET_LEDGER_PATH = DATA_DIR / EVENT_LLM_BUDGET_LEDGER_PATH
EVENT_LLM_EXTRACTOR_CACHE_PATH = (
    Path(_EVENT_LLM_EXTRACTOR_CACHE_PATH_RAW).expanduser() if _EVENT_LLM_EXTRACTOR_CACHE_PATH_RAW else None
)
if EVENT_LLM_EXTRACTOR_CACHE_PATH is not None and not EVENT_LLM_EXTRACTOR_CACHE_PATH.is_absolute():
    EVENT_LLM_EXTRACTOR_CACHE_PATH = DATA_DIR / EVENT_LLM_EXTRACTOR_CACHE_PATH

_BACKUP_DIR_RAW = os.getenv("RSI_BACKUP_DIR", "backups")
BACKUP_DIR = Path(_BACKUP_DIR_RAW).expanduser()
if not BACKUP_DIR.is_absolute():
    BACKUP_DIR = DATA_DIR / BACKUP_DIR
BACKUP_KEEP = int(os.getenv("RSI_BACKUP_KEEP", "14"))
BACKUP_STALE_HOURS = float(os.getenv("RSI_BACKUP_STALE_HOURS", "72"))
RESTORE_EXPECTED_TABLES = ("scans", "signals", "meta", "paper_trades")

_LOG_FILES_RAW = os.getenv("RSI_LOG_FILES", "scan.log,bot.log")
LOG_FILES: list[Path] = []
for _raw_log_path in (p.strip() for p in _LOG_FILES_RAW.split(",")):
    if not _raw_log_path:
        continue
    _log_path = Path(_raw_log_path).expanduser()
    if not _log_path.is_absolute():
        _log_path = DATA_DIR / _log_path
    LOG_FILES.append(_log_path)
LOG_ROTATE_MAX_BYTES = int(os.getenv("RSI_LOG_ROTATE_MAX_BYTES", str(5 * 1024 * 1024)))
LOG_ROTATE_KEEP = int(os.getenv("RSI_LOG_ROTATE_KEEP", "5"))

LAUNCHD_SCAN_LABEL = os.getenv("RSI_LAUNCHD_SCAN_LABEL", "com.nasrenkaraf.rsiscanner")
LAUNCHD_BOT_LABEL = os.getenv("RSI_LAUNCHD_BOT_LABEL", "com.nasrenkaraf.rsibot")
MAINTENANCE_LABEL = os.getenv("RSI_MAINTENANCE_LABEL", "com.nasrenkaraf.rsimaintenance")
MAINTENANCE_HOUR = int(os.getenv("RSI_MAINTENANCE_HOUR", "3"))
MAINTENANCE_MINUTE = int(os.getenv("RSI_MAINTENANCE_MINUTE", "45"))
_MAINTENANCE_LOG_RAW = os.getenv("RSI_MAINTENANCE_LOG", "maintenance.log")
MAINTENANCE_LOG = Path(_MAINTENANCE_LOG_RAW).expanduser()
if not MAINTENANCE_LOG.is_absolute():
    MAINTENANCE_LOG = DATA_DIR / MAINTENANCE_LOG
if MAINTENANCE_LOG not in LOG_FILES:
    LOG_FILES.append(MAINTENANCE_LOG)

_UNIVERSE_AUDIT_OUT_RAW = os.getenv("RSI_UNIVERSE_AUDIT_OUT", "universe_hygiene_latest.json")
UNIVERSE_AUDIT_OUT = Path(_UNIVERSE_AUDIT_OUT_RAW).expanduser()
if not UNIVERSE_AUDIT_OUT.is_absolute():
    UNIVERSE_AUDIT_OUT = DATA_DIR / UNIVERSE_AUDIT_OUT

_FIXTURE_DIR_RAW = os.getenv("RSI_FIXTURE_DIR", "")
FIXTURE_DIR = Path(_FIXTURE_DIR_RAW).expanduser() if _FIXTURE_DIR_RAW else None
if FIXTURE_DIR is not None and not FIXTURE_DIR.is_absolute():
    FIXTURE_DIR = DATA_DIR / FIXTURE_DIR

_BACKTEST_CACHE_DIR_RAW = os.getenv("RSI_BACKTEST_CACHE_DIR", "backtest_cache")
BACKTEST_CACHE_DIR = Path(_BACKTEST_CACHE_DIR_RAW).expanduser()
if not BACKTEST_CACHE_DIR.is_absolute():
    BACKTEST_CACHE_DIR = DATA_DIR / BACKTEST_CACHE_DIR


def redact_token(text: str) -> str:
    """Strip the Telegram bot token from a string before logging — it rides
    along inside request URLs in exception messages (e.g. getUpdates failures),
    which would otherwise leak the token into the log file."""
    token = TELEGRAM_BOT_TOKEN
    if token and token in text:
        return text.replace(token, "<bot-token>")
    return text


def has_notification_channel() -> bool:
    return bool(
        (TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_IDS)
        or DISCORD_WEBHOOK_URL
        or (SMTP_HOST and SMTP_USER and SMTP_PASS and EMAIL_TO)
    )


def validate() -> None:
    """Log warnings about config that will degrade the run. Non-fatal."""
    if not COINGECKO_API_KEY:
        log.warning(
            "No COINGECKO_API_KEY set — free tier is heavily rate-limited; "
            "4H data may be incomplete. A free demo key is strongly recommended."
        )
    if not has_notification_channel():
        log.warning("No notification channel configured — output will be console-only.")
    if RSI_OS >= RSI_OB:
        raise ValueError(f"RSI_OS ({RSI_OS}) must be below RSI_OB ({RSI_OB}).")
