"""Reporting for the legacy artifact doctor."""

from __future__ import annotations

from .runtime import *

def format_artifact_doctor_report(result: EventAlphaArtifactDoctorResult) -> str:
    lines = [
        "=" * 76,
        "EVENT ALPHA ARTIFACT DOCTOR (research artifact only)",
        "=" * 76,
        f"status: {result.status}",
        f"profile: {result.profile or 'any'}",
        f"namespace: {result.artifact_namespace or 'any'}",
        (
            "namespace_status: "
            f"{result.namespace_status or 'active'} "
            f"stale_deprecated={result.namespace_stale_deprecated} "
            f"superseded_by={result.namespace_superseded_by or 'none'}"
        ),
        f"strict: {str(result.strict).lower()}",
        f"strict_legacy: {str(result.strict_legacy).lower()}",
        doctor_report.phase_line(result),
        (
            "rows: "
            f"runs={result.run_rows} alerts={result.alert_rows} "
            f"feedback={result.feedback_rows} outcomes={result.outcome_rows} cards={result.card_files}"
        ),
        (
            "research cards: "
            f"research_card_files={result.research_card_files} "
            f"research_card_index_present={str(result.research_card_index_present).lower()} "
            f"cards_missing_lineage={result.cards_missing_lineage} "
            f"cards_missing_feedback_target={result.cards_missing_feedback_target}"
        ),
        doctor_report.schema_counter_line(result),
        *doctor_report.check_registry_lines(),
        (
            "shim hygiene: "
            "active_shim_modules_with_implementation_logic="
            f"{result.active_shim_modules_with_implementation_logic}"
        ),
        (
            "core opportunity coverage: "
            f"visible_core_opportunities={result.visible_core_opportunities} "
            f"core_opportunity_store_rows={result.core_opportunity_store_rows} "
            f"visible_core_opportunities_missing_store_rows={result.visible_core_opportunities_missing_store_rows} "
            f"duplicate_core_opportunity_store_rows={result.duplicate_core_opportunity_store_rows} "
            f"core_opportunity_store_rows_missing_card_path={result.core_opportunity_store_rows_missing_card_path} "
            f"visible_core_opportunities_missing_cards={result.visible_core_opportunities_missing_cards} "
            f"visible_core_opportunities_missing_feedback_targets={result.visible_core_opportunities_missing_feedback_targets} "
            f"alert_snapshots_missing_core_opportunity_id={result.alert_snapshots_missing_core_opportunity_id} "
            f"alert_snapshots_missing_feedback_target={result.alert_snapshots_missing_feedback_target} "
            f"core_cards_missing_store_row={result.core_cards_missing_store_row} "
            f"visible_core_cards_missing_store_row={result.visible_core_cards_missing_store_row} "
            f"orphan_core_opportunity_cards={result.orphan_core_opportunity_cards} "
            f"diagnostic_snapshots_with_fake_core_id={result.diagnostic_snapshots_with_fake_core_id} "
            f"alert_snapshots_core_id_missing_from_store={result.alert_snapshots_core_id_missing_from_store} "
            f"evidence_acquisition_core_id_missing_from_store={result.evidence_acquisition_core_id_missing_from_store} "
            f"card_primary_fields_mismatch_core_store={result.card_primary_fields_mismatch_core_store} "
            f"card_evidence_acquisition_count_mismatch={result.card_evidence_acquisition_count_mismatch} "
            f"evidence_acquisition_stale_validated_digest={result.evidence_acquisition_stale_validated_digest} "
            f"card_source_pack_mismatch_core_acquisition={result.card_source_pack_mismatch_core_acquisition} "
            f"card_primary_section_contains_support_row_blockers={result.card_primary_section_contains_support_row_blockers} "
            f"card_upgrade_text_inconsistent_with_final_level={result.card_upgrade_text_inconsistent_with_final_level} "
            f"audit_primary_impact_path_mismatch_core={result.audit_primary_impact_path_mismatch_core} "
            f"audit_source_pack_mismatch_core={result.audit_source_pack_mismatch_core} "
            f"card_market_confirmation_missing_but_core_has_market_confirmation={result.card_market_confirmation_missing_but_core_has_market_confirmation} "
            f"card_latest_source_unknown_but_accepted_evidence_exists={result.card_latest_source_unknown_but_accepted_evidence_exists} "
            f"quality_review_promoted_core_in_weak_section={result.quality_review_promoted_core_in_weak_section} "
            f"market_freshness_contradictory_summary={result.market_freshness_contradictory_summary} "
            f"quality_review_market_freshness_contradiction={result.quality_review_market_freshness_contradiction} "
            f"upgrade_candidates_include_high_priority={result.upgrade_candidates_include_high_priority} "
            f"daily_brief_card_group_mismatch_with_index={result.daily_brief_card_group_mismatch_with_index} "
            f"daily_brief_missing_selected_run={result.daily_brief_missing_selected_run} "
            f"daily_brief_selected_run_mismatch={result.daily_brief_selected_run_mismatch} "
            f"daily_brief_core_count_mismatch_store={result.daily_brief_core_count_mismatch_store} "
            f"daily_brief_research_review_lane_missing={result.daily_brief_research_review_lane_missing} "
            f"daily_brief_source_coverage_path_missing={result.daily_brief_source_coverage_path_missing} "
            "daily_brief_coinalyze_source_coverage_mismatch="
            f"{result.daily_brief_coinalyze_source_coverage_mismatch} "
            f"core_route_conflicts_with_opportunity_level={result.core_route_conflicts_with_opportunity_level} "
            f"alert_snapshot_route_mismatch_core_store={result.alert_snapshot_route_mismatch_core_store} "
            f"alert_snapshot_level_mismatch_core_store={result.alert_snapshot_level_mismatch_core_store} "
            f"alert_snapshot_live_confirmation_stale={result.alert_snapshot_live_confirmation_stale} "
            f"alert_snapshot_core_resolution_missing={result.alert_snapshot_core_resolution_missing} "
            f"alert_snapshot_pre_reconciliation_alertable={result.alert_snapshot_pre_reconciliation_alertable} "
            f"diagnostic_support_snapshot_alertable={result.diagnostic_support_snapshot_alertable} "
            f"diagnostic_support_snapshot_inherits_core_route={result.diagnostic_support_snapshot_inherits_core_route} "
            f"duplicate_alertable_snapshot_for_core={result.duplicate_alertable_snapshot_for_core} "
            f"canonical_snapshot_missing_for_visible_core={result.canonical_snapshot_missing_for_visible_core} "
            f"inbox_core_item_missing_card={result.inbox_core_item_missing_card} "
            f"inbox_core_item_uses_alert_id_feedback_target_when_core_target_exists={result.inbox_core_item_uses_alert_id_feedback_target_when_core_target_exists} "
            f"inbox_diagnostic_snapshot_visible_by_default={result.inbox_diagnostic_snapshot_visible_by_default} "
            f"audit_primary_snapshot_not_canonical_when_canonical_exists={result.audit_primary_snapshot_not_canonical_when_canonical_exists} "
            f"feedback_readiness_counts_diagnostic_as_required={result.feedback_readiness_counts_diagnostic_as_required} "
            f"live_validated_without_confirmation={result.live_validated_without_confirmation} "
            f"live_sector_digest_without_asset={result.live_sector_digest_without_asset} "
            f"live_rejected_results_promoted={result.live_rejected_results_promoted} "
            f"live_skipped_budget_promoted={result.live_skipped_budget_promoted} "
            f"raw_core_validated_without_confirmation={result.raw_core_validated_without_confirmation} "
            f"raw_core_source_only_narrative_validated={result.raw_core_source_only_narrative_validated} "
            f"raw_core_cryptopanic_tag_only_direct_path_confirmed={result.raw_core_cryptopanic_tag_only_direct_path_confirmed} "
            f"raw_core_suppressed_duplicate_validated_stale={result.raw_core_suppressed_duplicate_validated_stale} "
            f"confirmed_long_without_source_market={result.confirmed_long_without_source_market} "
            f"fade_short_without_crowding_exhaustion={result.fade_short_without_crowding_exhaustion} "
            f"early_long_without_fresh_strong_source={result.early_long_without_fresh_strong_source} "
            f"risk_only_missing_evidence_only={result.risk_only_missing_evidence_only} "
            f"cryptopanic_only_narrative_confirmed_lane={result.cryptopanic_only_narrative_confirmed_lane} "
            f"diagnostic_visible_default_operator_lane={result.diagnostic_visible_default_operator_lane} "
            f"core_missing_market_state_snapshot={result.core_missing_market_state_snapshot} "
            f"market_state_return_unit_missing={result.market_state_return_unit_missing} "
            f"market_state_possible_double_scaled={result.market_state_possible_double_scaled} "
            f"market_state_lane_possible_double_scaled={result.market_state_lane_possible_double_scaled} "
            f"market_anomaly_rows={result.market_anomaly_rows} "
            f"market_anomaly_missing_market_state_snapshot={result.market_anomaly_missing_market_state_snapshot} "
            f"market_anomaly_missing_market_state_class={result.market_anomaly_missing_market_state_class} "
            f"market_anomaly_confirmed_breakout_missing_evidence={result.market_anomaly_confirmed_breakout_missing_evidence} "
            f"market_anomaly_suspicious_illiquid_promoted_confirmed={result.market_anomaly_suspicious_illiquid_promoted_confirmed} "
            f"market_anomaly_created_alert_rows={result.market_anomaly_created_alert_rows} "
            f"market_anomaly_missing_freshness_status={result.market_anomaly_missing_freshness_status} "
            f"market_anomaly_needs_search_without_plan={result.market_anomaly_needs_search_without_plan} "
            f"official_exchange_candidate_rows={result.official_exchange_candidate_rows} "
            f"official_exchange_candidate_missing_source_fields={result.official_exchange_candidate_missing_source_fields} "
            f"official_exchange_listing_without_official_source={result.official_exchange_listing_without_official_source} "
            f"official_exchange_secret_leak={result.official_exchange_secret_leak} "
            f"official_exchange_delisting_long_research={result.official_exchange_delisting_long_research} "
            f"official_exchange_quote_asset_misclassified={result.official_exchange_quote_asset_misclassified} "
            f"official_exchange_major_pair_noise_promoted_early_long={result.official_exchange_major_pair_noise_promoted_early_long} "
            f"official_exchange_created_alert_rows={result.official_exchange_created_alert_rows} "
            "official_exchange_activation_missing_shared_schema="
            f"{result.official_exchange_activation_missing_shared_schema} "
            "official_exchange_activation_live_without_ledger="
            f"{result.official_exchange_activation_live_without_ledger} "
            "official_exchange_activation_signed_listener_secret_leak="
            f"{result.official_exchange_activation_signed_listener_secret_leak} "
            "official_exchange_activation_forbidden_side_effect_claim="
            f"{result.official_exchange_activation_forbidden_side_effect_claim} "
            "instrument_resolution_missing_canonical_id_when_fixture_has_it="
            f"{result.instrument_resolution_missing_canonical_id_when_fixture_has_it} "
            "instrument_resolution_quote_asset_misclassified="
            f"{result.instrument_resolution_quote_asset_misclassified} "
            "instrument_resolution_sector_visible_as_tradable="
            f"{result.instrument_resolution_sector_visible_as_tradable} "
            "instrument_resolution_coinalyze_symbol_unlinked="
            f"{result.instrument_resolution_coinalyze_symbol_unlinked} "
            f"scheduled_catalyst_rows={result.scheduled_catalyst_rows} "
            f"unlock_candidate_rows={result.unlock_candidate_rows} "
            f"derivatives_state_rows={result.derivatives_state_rows} "
            f"fade_review_candidate_rows={result.fade_review_candidate_rows} "
            f"unlock_without_structured_evidence={result.unlock_without_structured_evidence} "
            f"unlock_missing_event_time={result.unlock_missing_event_time} "
            f"unlock_promoted_without_size_metrics={result.unlock_promoted_without_size_metrics} "
            f"media_unlock_promoted_structured={result.media_unlock_promoted_structured} "
            f"stale_completed_catalyst_upcoming={result.stale_completed_catalyst_upcoming} "
            f"calendar_event_missing_source_url={result.calendar_event_missing_source_url} "
            f"cryptopanic_unlock_proof={result.cryptopanic_unlock_proof} "
            f"scheduled_catalyst_created_alert_rows={result.scheduled_catalyst_created_alert_rows} "
            f"fade_review_without_completed_move={result.fade_review_without_completed_move} "
            f"fade_review_without_crowding_exhaustion={result.fade_review_without_crowding_exhaustion} "
            f"fade_review_created_triggered_fade={result.fade_review_created_triggered_fade} "
            f"fade_review_created_normal_rsi_signal={result.fade_review_created_normal_rsi_signal} "
            f"fade_review_notification_missing_disclaimer={result.fade_review_notification_missing_disclaimer} "
            f"derivatives_artifact_secret_leak={result.derivatives_artifact_secret_leak} "
            f"derivatives_state_missing_freshness_status={result.derivatives_state_missing_freshness_status} "
            "derivatives_metric_claim_implemented_missing="
            f"{result.derivatives_metric_claim_implemented_missing} "
            f"derivatives_unit_metadata_missing={result.derivatives_unit_metadata_missing} "
            "stale_derivatives_snapshot_promoted_fade_review="
            f"{result.stale_derivatives_snapshot_promoted_fade_review} "
            f"confirmed_long_crowded_without_warning={result.confirmed_long_crowded_without_warning} "
            f"integrated_radar_candidate_rows={result.integrated_radar_candidate_rows} "
            f"integrated_candidate_missing_opportunity_type={result.integrated_candidate_missing_opportunity_type} "
            f"integrated_candidate_missing_market_state_snapshot={result.integrated_candidate_missing_market_state_snapshot} "
            f"integrated_confirmed_long_without_source_market={result.integrated_confirmed_long_without_source_market} "
            f"integrated_early_long_without_fresh_strong_source={result.integrated_early_long_without_fresh_strong_source} "
            f"integrated_fade_without_crowding_exhaustion={result.integrated_fade_without_crowding_exhaustion} "
            f"integrated_risk_without_evidence={result.integrated_risk_without_evidence} "
            f"integrated_market_anomaly_confirmed={result.integrated_market_anomaly_confirmed} "
            f"integrated_cryptopanic_confirmed={result.integrated_cryptopanic_confirmed} "
            f"integrated_major_pair_early_long={result.integrated_major_pair_early_long} "
            f"integrated_input_manifest_missing={result.integrated_input_manifest_missing} "
            f"integrated_source_coverage_json_missing={result.integrated_source_coverage_json_missing} "
            f"integrated_candidate_core_missing={result.integrated_candidate_core_missing} "
            f"integrated_candidate_core_opportunity_type_mismatch={result.integrated_candidate_core_opportunity_type_mismatch} "
            f"integrated_candidate_core_market_state_mismatch={result.integrated_candidate_core_market_state_mismatch} "
            f"integrated_candidate_core_route_level_mismatch={result.integrated_candidate_core_route_level_mismatch} "
            f"integrated_candidate_core_reason_code_loss={result.integrated_candidate_core_reason_code_loss} "
            f"integrated_candidate_core_source_url_loss={result.integrated_candidate_core_source_url_loss} "
            f"integrated_candidate_core_official_event_loss={result.integrated_candidate_core_official_event_loss} "
            f"integrated_candidate_core_scheduled_event_loss={result.integrated_candidate_core_scheduled_event_loss} "
            f"integrated_candidate_core_unlock_event_loss={result.integrated_candidate_core_unlock_event_loss} "
            f"integrated_candidate_core_derivatives_loss={result.integrated_candidate_core_derivatives_loss} "
            f"integrated_candidate_card_opportunity_type_mismatch={result.integrated_candidate_card_opportunity_type_mismatch} "
            f"integrated_candidate_card_why_now_mismatch={result.integrated_candidate_card_why_now_mismatch} "
            f"integrated_major_pair_card_early_long={result.integrated_major_pair_card_early_long} "
            f"integrated_card_generic_lane_override={result.integrated_card_generic_lane_override} "
            f"card_opportunity_lane_core_mismatch={result.card_opportunity_lane_core_mismatch} "
            f"integrated_candidate_card_official_event_missing={result.integrated_candidate_card_official_event_missing} "
            f"integrated_candidate_card_source_url_missing={result.integrated_candidate_card_source_url_missing} "
            f"integrated_candidate_core_crowding_metadata_loss={result.integrated_candidate_core_crowding_metadata_loss} "
            f"derivatives_card_metric_claim_without_data={result.derivatives_card_metric_claim_without_data} "
            f"integrated_coinalyze_crowding_card_missing={result.integrated_coinalyze_crowding_card_missing} "
            f"integrated_coinalyze_loaded_no_rows_attached={result.integrated_coinalyze_loaded_no_rows_attached} "
            f"integrated_coinalyze_missing_skip_reason={result.integrated_coinalyze_missing_skip_reason} "
            f"integrated_coinalyze_stale_loaded_without_warning={result.integrated_coinalyze_stale_loaded_without_warning} "
            f"integrated_coinalyze_loaded_from_stale_namespace={result.integrated_coinalyze_loaded_from_stale_namespace} "
            f"integrated_fade_card_crowding_unknown={result.integrated_fade_card_crowding_unknown} "
            f"integrated_fade_card_missing_disclaimer={result.integrated_fade_card_missing_disclaimer} "
            f"integrated_confirmed_long_crowding_warning_hidden={result.integrated_confirmed_long_crowding_warning_hidden} "
            f"integrated_market_confirmation_display_contradiction={result.integrated_market_confirmation_display_contradiction} "
            f"integrated_derivatives_display_contradiction={result.integrated_derivatives_display_contradiction} "
            f"integrated_manifest_mixed_timestamp_pair={result.integrated_manifest_mixed_timestamp_pair} "
            f"integrated_core_silent_upgrade={result.integrated_core_silent_upgrade} "
            f"integrated_diagnostic_visible_in_default_operator_section={result.integrated_diagnostic_visible_in_default_operator_section} "
            f"integrated_preview_missing_disclaimer={result.integrated_preview_missing_disclaimer} "
            f"integrated_delivery_ledger_missing={result.integrated_delivery_ledger_missing} "
            f"integrated_preview_lane_mismatch={result.integrated_preview_lane_mismatch} "
            f"integrated_delivery_missing_disclaimer={result.integrated_delivery_missing_disclaimer} "
            f"integrated_delivery_sent_in_no_send={result.integrated_delivery_sent_in_no_send} "
            f"integrated_delivery_side_effect_flag={result.integrated_delivery_side_effect_flag} "
            f"integrated_delivery_missing_skip_reasons={result.integrated_delivery_missing_skip_reasons} "
            f"integrated_delivery_card_path_absolute={result.integrated_delivery_card_path_absolute} "
            f"integrated_delivery_card_path_not_rendered={result.integrated_delivery_card_path_not_rendered} "
            f"integrated_operator_markdown_absolute_path={result.integrated_operator_markdown_absolute_path} "
            f"operator_structured_path_absolute={result.operator_structured_path_absolute} "
            f"integrated_legacy_preview_alerts_wording={result.integrated_legacy_preview_alerts_wording} "
            f"integrated_manifest_daily_brief_unavailable={result.integrated_manifest_daily_brief_unavailable} "
            f"integrated_outcome_missing_for_candidate={result.integrated_outcome_missing_for_candidate} "
            f"integrated_outcome_side_effect_flag={result.integrated_outcome_side_effect_flag} "
            f"integrated_outcome_schema_missing={result.integrated_outcome_schema_missing} "
            f"integrated_outcome_missing_identity={result.integrated_outcome_missing_identity} "
            f"integrated_outcome_returns_without_price={result.integrated_outcome_returns_without_price} "
            f"integrated_outcome_diagnostic_in_performance={result.integrated_outcome_diagnostic_in_performance} "
            f"integrated_calibration_diagnostic_in_main_priors={result.integrated_calibration_diagnostic_in_main_priors} "
            f"integrated_calibration_prior_safety_missing={result.integrated_calibration_prior_safety_missing} "
            f"integrated_calibration_legacy_alias_top_level={result.integrated_calibration_legacy_alias_top_level} "
            f"integrated_outcome_return_double_scaled={result.integrated_outcome_return_double_scaled} "
            f"integrated_outcome_missing_data_unlabeled={result.integrated_outcome_missing_data_unlabeled} "
            f"integrated_outcome_thesis_move_missing={result.integrated_outcome_thesis_move_missing} "
            "integrated_outcome_card_thesis_interpretation_missing="
            f"{result.integrated_outcome_card_thesis_interpretation_missing} "
            f"integrated_outcome_card_trade_wording={result.integrated_outcome_card_trade_wording} "
            "integrated_performance_diagnostic_in_main_aggregate="
            f"{result.integrated_performance_diagnostic_in_main_aggregate} "
            f"integrated_performance_auto_apply_enabled={result.integrated_performance_auto_apply_enabled} "
            "integrated_performance_low_sample_missing_warning="
            f"{result.integrated_performance_low_sample_missing_warning} "
            f"integrated_performance_trade_pnl_wording={result.integrated_performance_trade_pnl_wording} "
            f"integrated_created_normal_rsi_signal={result.integrated_created_normal_rsi_signal} "
            f"integrated_created_triggered_fade={result.integrated_created_triggered_fade} "
            f"source_coverage_report_missing={result.source_coverage_report_missing} "
            f"source_coverage_provider_status_unknown={result.source_coverage_provider_status_unknown} "
            f"source_coverage_provider_marked_healthy_without_observation={result.source_coverage_provider_marked_healthy_without_observation} "
            f"source_coverage_category_priority_missing={result.source_coverage_category_priority_missing} "
            f"source_coverage_readiness_link_missing={result.source_coverage_readiness_link_missing} "
            f"source_coverage_context_provider_ranked_above_lane_critical={result.source_coverage_context_provider_ranked_above_lane_critical} "
            "source_coverage_coinalyze_missing_linked_artifact="
            f"{result.source_coverage_coinalyze_missing_linked_artifact} "
            "source_coverage_bybit_announcements_missing_linked_artifact="
            f"{result.source_coverage_bybit_announcements_missing_linked_artifact} "
            "source_coverage_unlock_calendar_missing_linked_artifact="
            f"{result.source_coverage_unlock_calendar_missing_linked_artifact} "
            f"live_provider_readiness_missing={result.live_provider_readiness_missing} "
            f"live_provider_readiness_secret_leak={result.live_provider_readiness_secret_leak} "
            f"live_provider_readiness_live_calls_allowed_in_smoke={result.live_provider_readiness_live_calls_allowed_in_smoke} "
            f"live_provider_readiness_configured_missing_env={result.live_provider_readiness_configured_missing_env} "
            f"coinalyze_preflight_secret_leak={result.coinalyze_preflight_secret_leak} "
            f"coinalyze_preflight_live_call_allowed_in_smoke={result.coinalyze_preflight_live_call_allowed_in_smoke} "
            f"coinalyze_preflight_configured_missing_env={result.coinalyze_preflight_configured_missing_env} "
            f"coinalyze_preflight_ready_without_request_ledger={result.coinalyze_preflight_ready_without_request_ledger} "
            f"coinalyze_preflight_missing_fixture_parser_status={result.coinalyze_preflight_missing_fixture_parser_status} "
            f"coinalyze_preflight_forbidden_side_effect_claim={result.coinalyze_preflight_forbidden_side_effect_claim} "
            f"coinalyze_rehearsal_secret_leak={result.coinalyze_rehearsal_secret_leak} "
            f"coinalyze_rehearsal_live_without_ledger={result.coinalyze_rehearsal_live_without_ledger} "
            "coinalyze_rehearsal_live_call_allowed_in_smoke="
            f"{result.coinalyze_rehearsal_live_call_allowed_in_smoke} "
            "coinalyze_rehearsal_live_without_explicit_allow="
            f"{result.coinalyze_rehearsal_live_without_explicit_allow} "
            f"coinalyze_rehearsal_request_budget_exceeded={result.coinalyze_rehearsal_request_budget_exceeded} "
            "coinalyze_rehearsal_success_without_derivatives_state="
            f"{result.coinalyze_rehearsal_success_without_derivatives_state} "
            "coinalyze_rehearsal_success_without_crowding_candidates="
            f"{result.coinalyze_rehearsal_success_without_crowding_candidates} "
            "coinalyze_provider_health_healthy_without_successful_ledger="
            f"{result.coinalyze_provider_health_healthy_without_successful_ledger} "
            "coinalyze_rehearsal_forbidden_side_effect_claim="
            f"{result.coinalyze_rehearsal_forbidden_side_effect_claim} "
            "coinalyze_supported_metric_implemented_missing_state="
            f"{result.coinalyze_supported_metric_implemented_missing_state} "
            f"bybit_announcements_preflight_secret_leak={result.bybit_announcements_preflight_secret_leak} "
            "bybit_announcements_preflight_live_call_allowed_in_smoke="
            f"{result.bybit_announcements_preflight_live_call_allowed_in_smoke} "
            "bybit_announcements_preflight_missing_fixture_parser_status="
            f"{result.bybit_announcements_preflight_missing_fixture_parser_status} "
            f"bybit_announcements_rehearsal_secret_leak={result.bybit_announcements_rehearsal_secret_leak} "
            "bybit_announcements_rehearsal_live_without_ledger="
            f"{result.bybit_announcements_rehearsal_live_without_ledger} "
            "bybit_announcements_rehearsal_live_without_explicit_allow="
            f"{result.bybit_announcements_rehearsal_live_without_explicit_allow} "
            "bybit_announcements_rehearsal_unsupported_params="
            f"{result.bybit_announcements_rehearsal_unsupported_params} "
            "bybit_announcements_rehearsal_forbidden_side_effect_claim="
            f"{result.bybit_announcements_rehearsal_forbidden_side_effect_claim} "
            "unlock_calendar_preflight_secret_leak="
            f"{result.unlock_calendar_preflight_secret_leak} "
            "unlock_calendar_preflight_live_without_ledger="
            f"{result.unlock_calendar_preflight_live_without_ledger} "
            "unlock_calendar_preflight_live_call_allowed_in_smoke="
            f"{result.unlock_calendar_preflight_live_call_allowed_in_smoke} "
            "unlock_calendar_preflight_missing_fixture_parser_status="
            f"{result.unlock_calendar_preflight_missing_fixture_parser_status} "
            "unlock_calendar_preflight_forbidden_side_effect_claim="
            f"{result.unlock_calendar_preflight_forbidden_side_effect_claim} "
            f"source_pack_provider_status_missing={result.source_pack_provider_status_missing} "
            f"missing_provider_recommendations_missing={result.missing_provider_recommendations_missing} "
            f"degraded_provider_absence_marked_meaningful={result.degraded_provider_absence_marked_meaningful} "
            f"cryptopanic_configured_but_not_observed={result.cryptopanic_configured_but_not_observed} "
            f"cryptopanic_used_but_no_source_coverage_entry={result.cryptopanic_used_but_no_source_coverage_entry} "
            f"cryptopanic_accepted_evidence_missing_from_card={result.cryptopanic_accepted_evidence_missing_from_card} "
            f"cryptopanic_rejected_only_promoted={result.cryptopanic_rejected_only_promoted} "
            f"cryptopanic_token_printed_or_unredacted={result.cryptopanic_token_printed_or_unredacted} "
            f"cryptopanic_growth_unsupported_param_used={result.cryptopanic_growth_unsupported_param_used} "
            f"cryptopanic_duplicate_request_key={result.cryptopanic_duplicate_request_key} "
            f"cryptopanic_invalid_currency_code={result.cryptopanic_invalid_currency_code} "
            f"cryptopanic_empty_currency_request={result.cryptopanic_empty_currency_request} "
            f"cryptopanic_coin_id_sent_as_currency={result.cryptopanic_coin_id_sent_as_currency} "
            f"cryptopanic_all_requests_failed={result.cryptopanic_all_requests_failed} "
            f"cryptopanic_json_parse_errors={result.cryptopanic_json_parse_errors} "
            f"cryptopanic_configured_but_unusable={result.cryptopanic_configured_but_unusable} "
            f"cryptopanic_status_code_missing_on_http_failure={result.cryptopanic_status_code_missing_on_http_failure} "
            f"cryptopanic_body_excerpt_unredacted_token={result.cryptopanic_body_excerpt_unredacted_token} "
            f"cryptopanic_quota_exceeded={result.cryptopanic_quota_exceeded} "
            f"cryptopanic_request_ledger_missing_when_used={result.cryptopanic_request_ledger_missing_when_used} "
            f"cryptopanic_success_with_backoff_status={result.cryptopanic_success_with_backoff_status} "
            "cryptopanic_restore_token_recommendation_when_configured="
            f"{result.cryptopanic_restore_token_recommendation_when_configured} "
            f"evidence_count_mismatch={result.evidence_count_mismatch} "
            f"visible_sector_core_without_config={result.visible_sector_core_without_config} "
            f"duplicate_proxy_core_rows={result.duplicate_proxy_core_rows}"
        ),
        (
            "snapshot lineage: "
            f"matching={result.runs_with_matching_snapshots} "
            f"missing={result.runs_with_missing_snapshots} "
            f"external={result.runs_with_external_snapshot_paths}"
        ),
        (
            "legacy rows: "
            f"skipped={result.legacy_rows_skipped} counted={result.legacy_rows_counted}"
        ),
        (
            "notification deliveries: "
            f"rows={result.delivery_rows} partial={result.deliveries_partial_delivered} failed={result.deliveries_failed} "
            f"status_missing={result.delivery_status_missing} "
            f"status_detail_missing={result.delivery_status_detail_missing} "
            f"mode_missing={result.delivery_mode_missing} "
            f"state_inconsistent={result.delivery_state_inconsistent} "
            f"would_send_inconsistent={result.delivery_would_send_sent_failed_inconsistent} "
            f"latest_run_id={result.latest_run_id or 'none'} "
            f"strict_scope={result.delivery_strict_scope} "
            f"latest_run_rows={result.latest_run_delivery_rows} "
            f"stale_rows={result.stale_delivery_rows} "
            f"legacy_rows={result.legacy_delivery_rows} "
            f"identity_mismatch={result.delivery_identity_mismatch_core_store} "
            f"core_missing={result.delivery_core_id_missing} "
            f"stale_core_missing={result.stale_delivery_identity_missing_core} "
            f"legacy_pre_core_identity={result.legacy_pre_core_delivery_identity} "
            f"feedback_missing={result.delivery_feedback_target_missing} "
            f"card_missing={result.delivery_card_path_missing} "
            f"alert_id_not_canonical={result.delivery_alert_id_not_canonical} "
            f"digest_without_confirmation={result.digest_item_without_live_confirmation} "
            f"digest_rejected_only={result.digest_item_rejected_results_only} "
            f"strategic_broad_digest={result.strategic_broad_asset_digest_without_confirmation} "
            f"unconfirmed_narrative_daily_digest={result.unconfirmed_narrative_daily_digest} "
            "single_source_no_market_fan_token_digest="
            f"{result.single_source_no_market_fan_token_digest} "
            f"preview_missing={result.notification_preview_missing} "
            f"preview_relpath_missing={result.notification_preview_relpath_missing} "
            f"preview_unresolvable={result.notification_preview_path_unresolvable} "
            f"preview_run_mismatch={result.notification_preview_run_summary_mismatch} "
            f"preview_llm_mismatch={result.notification_preview_llm_summary_mismatch} "
            f"preview_lane_mismatch={result.notification_preview_lane_counts_mismatch} "
            f"preview_core_mismatch={result.notification_preview_core_count_mismatch} "
            f"preview_alertable_mismatch={result.notification_preview_alertable_count_mismatch} "
            f"preview_missing_send_guard={result.notification_preview_missing_send_guard_status} "
            f"preview_send_guard_missing={result.notification_preview_send_guard_status_missing} "
            f"preview_no_send_unclear={result.notification_preview_no_send_status_unclear} "
            f"preview_legacy_alerts_wording={result.notification_preview_legacy_alerts_wording} "
            f"raw_debug_dump={result.telegram_message_contains_raw_debug_dump} "
            f"absolute_path={result.telegram_message_contains_absolute_path} "
            f"research_review_missing_label={result.research_review_digest_missing_confirmation_label} "
            f"research_review_alertable={result.research_review_digest_contains_strict_alertable} "
            f"research_review_hard_gated={result.research_review_digest_contains_hard_gated_candidate} "
            f"research_review_too_many={result.research_review_digest_too_many_items} "
            f"research_review_feedback_missing={result.research_review_digest_missing_feedback_target} "
            f"research_review_skipped_without_reason={result.research_review_digest_skipped_without_reason} "
            f"research_review_missing_family_summary={result.research_review_digest_missing_family_summary} "
            "research_review_duplicate_visible_family_summary="
            f"{result.research_review_digest_duplicate_visible_family_summary} "
            f"research_review_absolute_path={result.research_review_digest_absolute_path} "
            f"body_card_mismatch={result.notification_body_card_mismatch_canonical} "
            f"body_feedback_mismatch={result.notification_body_feedback_mismatch_canonical} "
            f"body_hypothesis_target={result.research_review_body_uses_hypothesis_target_when_core_exists} "
            f"research_review_lane_missing={result.research_review_digest_enabled_but_lane_missing} "
            f"research_review_no_delivery={result.research_review_digest_candidates_without_delivery}"
        ),
        (
            "quality fields: "
            f"missing_total={result.quality_fields_missing_count} "
            f"hypotheses_missing_verdict={result.hypothesis_rows_missing_opportunity_verdict} "
            f"watchlist_missing={result.watchlist_rows_missing_quality_fields} "
            f"alerts_missing={result.alert_rows_missing_quality_fields} "
            f"fresh_hypotheses_missing_top_level={result.fresh_hypothesis_rows_missing_top_level_quality} "
            f"fresh_watchlist_missing_top_level={result.fresh_watchlist_rows_missing_top_level_quality} "
            f"fresh_alerts_missing_top_level={result.fresh_alert_rows_missing_top_level_quality} "
            f"legacy_quality_missing={result.legacy_quality_missing_rows}"
        ),
        (
            "quality gate conflicts: "
            f"alertable_route_conflicts_with_opportunity_level={result.alertable_route_conflicts_with_opportunity_level} "
            f"fresh_quality_route_conflict_rows={result.fresh_quality_route_conflict_rows} "
            f"legacy_quality_conflict_rows={result.legacy_quality_conflict_rows} "
            f"alert_rows_missing_final_route={result.alert_rows_missing_final_route} "
            f"fresh_alert_rows_missing_final_route={result.fresh_alert_rows_missing_final_route}"
        ),
        (
            "watchlist quality state: "
            f"watchlist_state_conflicts_with_quality={result.watchlist_state_conflicts_with_quality} "
            f"universal={result.universal_watchlist_state_conflicts} "
            f"non_hypothesis={result.non_hypothesis_watchlist_quality_conflicts} "
            f"hypothesis={result.hypothesis_watchlist_quality_conflicts} "
            f"quality_capped={result.quality_capped_watchlist_rows} "
            f"active_watchlist_rows_quality_capped={result.active_watchlist_rows_quality_capped} "
            f"fresh_watchlist_state_conflict_rows={result.fresh_watchlist_state_conflict_rows} "
            f"legacy_watchlist_conflicts={result.legacy_watchlist_conflicts}"
        ),
        (
            "incident linkage: "
            f"hypothesis_rows_missing_incident_id={result.hypothesis_rows_missing_incident_id} "
            f"watchlist_hypothesis_rows_missing_incident_id={result.watchlist_hypothesis_rows_missing_incident_id} "
            f"alert_hypothesis_rows_missing_incident_id={result.alert_hypothesis_rows_missing_incident_id} "
            f"incident_rows_without_linked_hypotheses={result.incident_rows_without_linked_hypotheses} "
            f"incident_rows_without_linked_watchlist={result.incident_rows_without_linked_watchlist} "
            f"canonical_unlinked_incidents={result.canonical_unlinked_incidents} "
            f"active_incident_without_qualified_link={result.active_incident_without_qualified_link} "
            f"linked_incident_without_qualified_link={result.linked_incident_without_qualified_link} "
            f"weak_unqualified_incident_links={result.weak_unqualified_incident_links} "
            f"quality_blocked_links_present={result.quality_blocked_links_present} "
            f"quality_blocked_links_promoting_incident={result.quality_blocked_links_promoting_incident} "
            f"diagnostic_incident_rows={result.diagnostic_incident_rows} "
            f"raw_observation_incident_rows={result.raw_observation_incident_rows} "
            f"external_context_incident_rows={result.external_context_incident_rows} "
            f"rejected_incident_rows={result.rejected_incident_rows} "
            f"incident_relevance_missing={result.incident_relevance_missing} "
            f"invalid_canonical_incident_rows={result.invalid_canonical_incident_rows} "
            f"garbage_primary_subject_incidents={result.garbage_primary_subject_incidents} "
            f"fresh_blockers={result.fresh_incident_linkage_blockers} "
            f"legacy_warnings={result.legacy_incident_linkage_warnings}"
        ),
        "",
        "blockers:",
    ]
    lines.extend(f"- {item}" for item in result.blockers) if result.blockers else lines.append("- none")
    lines.extend(["", "warnings:"])
    lines.extend(f"- {item}" for item in result.warnings) if result.warnings else lines.append("- none")
    lines.append("Doctor reports artifact hygiene only; it does not send, trade, paper trade, or alter tiers.")
    return "\n".join(lines).rstrip()

__all__ = (
    'format_artifact_doctor_report',
)
