"""Ordered row-type and filename mappings for the Event Alpha schema registry."""

from __future__ import annotations


ROW_TYPE_TO_SCHEMA_ID = {
    "event_core_opportunity": "core_opportunity_v1",
    "event_integrated_radar_candidate": "integrated_radar_candidate_v1",
    "event_alpha_notification_delivery": "notification_delivery_v1",
    "event_integrated_radar_notification_delivery": "integrated_notification_delivery_v1",
    "event_live_provider_activation_readiness": "provider_readiness_v1",
    "event_official_exchange_activation": "provider_readiness_v1",
    "event_coinalyze_preflight": "provider_preflight_v1",
    "event_coinalyze_rehearsal_report": "provider_preflight_v1",
    "event_bybit_announcements_preflight": "provider_preflight_v1",
    "event_bybit_announcements_rehearsal_report": "provider_preflight_v1",
    "event_unlock_calendar_preflight": "provider_preflight_v1",
    "event_dex_onchain_readiness": "provider_readiness_v1",
    "coinalyze_request_ledger": "coinalyze_request_ledger_v1",
    "derivatives_state_snapshot": "derivatives_state_snapshot_v1",
    "event_derivatives_crowding_candidate": "derivatives_crowding_candidate_v1",
    "event_fade_short_review_candidate": "fade_review_candidate_v1",
    "fade_short_review_candidate": "fade_review_candidate_v1",
    "event_market_state_snapshot": "market_state_snapshot_v1",
    "event_targeted_market_refresh_ledger": "targeted_market_refresh_ledger_v1",
    "event_targeted_market_refresh_report": "targeted_market_refresh_report_v1",
    "event_market_anomaly": "market_anomaly_v1",
    "event_market_anomaly_catalyst_search_queue": "market_anomaly_v1",
    "event_official_exchange_event": "official_exchange_event_v1",
    "official_exchange_event": "official_exchange_event_v1",
    "exchange_announcement": "official_exchange_event_v1",
    "event_scheduled_catalyst": "scheduled_catalyst_event_v1",
    "scheduled_catalyst": "scheduled_catalyst_event_v1",
    "event_unified_calendar_event": "unified_calendar_event_v1",
    "event_unlock_candidate": "unlock_event_v1",
    "unlock_candidate": "unlock_event_v1",
    "event_integrated_radar_outcome": "outcome_row_v1",
    "event_alpha_feedback": "feedback_row_v1",
    "event_alpha_calibration_priors": "feedback_calibration_prior_v2",
    "event_integrated_radar_calibration_priors": "calibration_prior_v1",
    "event_radar_provider_performance": "calibration_prior_v1",
    "event_alpha_namespace_status": "namespace_status_v1",
    "event_alpha_operator_state": "operator_state_v1",
    "event_alpha_run": "run_ledger_v1",
    "event_alpha_daily_burn_in_run": "event_alpha_daily_burn_in_run_v1",
    "event_alpha_candidate_mode_manifest": "event_alpha_candidate_mode_manifest_v1",
    "event_alpha_daily_review_inbox": "event_alpha_daily_review_inbox_v1",
    "event_alpha_burn_in_scorecard": "event_alpha_burn_in_scorecard_v1",
    "event_alpha_burn_in_measurement_dashboard": "event_alpha_burn_in_measurement_dashboard_v1",
    "event_alpha_source_yield_report": "event_alpha_source_yield_report_v1",
    "event_alpha_burn_in_archive_manifest": "event_alpha_burn_in_archive_manifest_v1",
    "event_alpha_burn_in_namespace_policy": "event_alpha_burn_in_namespace_policy_v1",
}

FILENAME_TO_SCHEMA_ID = {
    "event_core_opportunities.jsonl": "core_opportunity_v1",
    "event_integrated_radar_candidates.jsonl": "integrated_radar_candidate_v1",
    "event_alpha_notification_deliveries.jsonl": "notification_delivery_v1",
    "event_integrated_radar_notification_deliveries.jsonl": "integrated_notification_delivery_v1",
    "event_alpha_source_coverage.json": "source_coverage_v1",
    "event_live_provider_readiness.json": "provider_readiness_v1",
    "event_live_provider_activation_readiness.json": "provider_readiness_v1",
    "event_coinalyze_preflight.json": "provider_preflight_v1",
    "event_coinalyze_rehearsal_report.json": "provider_preflight_v1",
    "event_bybit_announcements_preflight.json": "provider_preflight_v1",
    "event_bybit_announcements_rehearsal_report.json": "provider_preflight_v1",
    "event_unlock_calendar_preflight.json": "provider_preflight_v1",
    "event_official_exchange_activation.json": "provider_readiness_v1",
    "event_dex_onchain_readiness.json": "provider_readiness_v1",
    "event_coinalyze_request_ledger.jsonl": "coinalyze_request_ledger_v1",
    "event_bybit_announcements_request_ledger.jsonl": "provider_request_ledger_v1",
    "event_derivatives_state.jsonl": "derivatives_state_snapshot_v1",
    "event_derivatives_crowding_candidates.jsonl": "derivatives_crowding_candidate_v1",
    "event_fade_short_review_candidates.jsonl": "fade_review_candidate_v1",
    "event_market_state_snapshots.jsonl": "market_state_snapshot_v1",
    "event_targeted_market_refresh_ledger.jsonl": "targeted_market_refresh_ledger_v1",
    "event_targeted_market_refresh_report.json": "targeted_market_refresh_report_v1",
    "event_market_anomalies.jsonl": "market_anomaly_v1",
    "event_market_anomaly_catalyst_search_queue.jsonl": "market_anomaly_v1",
    "event_exchange_announcements.jsonl": "official_exchange_event_v1",
    "event_official_exchange_events.jsonl": "official_exchange_event_v1",
    "event_scheduled_catalysts.jsonl": "scheduled_catalyst_event_v1",
    "event_unified_calendar_events.jsonl": "unified_calendar_event_v1",
    "event_unlock_candidates.jsonl": "unlock_event_v1",
    "event_integrated_radar_outcomes.jsonl": "outcome_row_v1",
    "event_alpha_outcomes.jsonl": "outcome_row_v1",
    "event_alpha_feedback.jsonl": "feedback_row_v1",
    "event_alpha_priors.json": "feedback_calibration_prior_v2",
    "event_integrated_radar_calibration_priors.json": "calibration_prior_v1",
    "event_radar_provider_performance.json": "calibration_prior_v1",
    "event_alpha_namespace_status.json": "namespace_status_v1",
    "event_alpha_operator_state.json": "operator_state_v1",
    "event_alpha_runs.jsonl": "run_ledger_v1",
    "event_alpha_daily_burn_in_run.json": "event_alpha_daily_burn_in_run_v1",
    "event_alpha_candidate_mode_manifest.json": "event_alpha_candidate_mode_manifest_v1",
    "event_alpha_daily_review_inbox.json": "event_alpha_daily_review_inbox_v1",
    "event_alpha_burn_in_scorecard.json": "event_alpha_burn_in_scorecard_v1",
    "event_alpha_burn_in_measurement_dashboard.json": "event_alpha_burn_in_measurement_dashboard_v1",
    "event_alpha_source_yield_report.json": "event_alpha_source_yield_report_v1",
    "event_alpha_burn_in_archive_manifest.json": "event_alpha_burn_in_archive_manifest_v1",
    "event_alpha_burn_in_namespace_policy.json": "event_alpha_burn_in_namespace_policy_v1",
}


__all__ = ("FILENAME_TO_SCHEMA_ID", "ROW_TYPE_TO_SCHEMA_ID")
