"""Deterministic fixture rows for the Event Alpha notification smoke."""

from __future__ import annotations

from .bindings import *  # noqa: F403


def _velvet_entry(now: datetime) -> event_watchlist.EventWatchlistEntry:
    return event_watchlist.EventWatchlistEntry(
        schema_version=event_watchlist.WATCHLIST_SCHEMA_VERSION,
        row_type="event_watchlist_state",
        key="fixture-spacex|velvet|proxy_attention",
        cluster_id="fixture-spacex|proxy_attention|2026-06-15",
        event_id="fixture-notify-velvet",
        coin_id="velvet",
        symbol="VELVET",
        relationship_type="venue_value_capture",
        external_asset="SpaceX",
        event_time=now.isoformat(),
        state=event_watchlist.EventWatchlistState.HIGH_PRIORITY.value,
        previous_state=event_watchlist.EventWatchlistState.WATCHLIST.value,
        first_seen_at=now.isoformat(),
        last_seen_at=now.isoformat(),
        source_count=2,
        highest_score=92,
        latest_score=92,
        latest_tier="HIGH_PRIORITY_WATCH",
        latest_event_name="VELVET offers SpaceX pre-IPO tokenized stock exposure",
        latest_source="CryptoPanic fixture",
        latest_playbook_type="proxy_attention",
        latest_rule_playbook_type="proxy_attention",
        latest_effective_playbook_type="proxy_attention",
        latest_playbook_score=92,
        latest_playbook_action="high_priority_watch",
        latest_market_snapshot={"price": 1.0, "return_24h": 0.42, "volume_zscore_24h": 5.2},
        latest_score_components={
            "core_opportunity_id": "agg:fixture-velvet-spacex",
            "hypothesis_id": "hypothesis:fixture-velvet-spacex",
            "external_catalyst": 92,
            "market_move_volume": 88,
            "impact_path_type": "venue_value_capture",
            "impact_path_strength": "strong",
            "candidate_role": "proxy_venue",
            "source_class": "cryptopanic_tagged",
            "evidence_specificity": "direct_token_mechanism",
            "evidence_quality_score": 91,
            "market_confirmation_score": 88,
            "market_confirmation_level": "strong",
            "market_context_freshness_status": "fresh",
            "opportunity_score_final": 92,
            "opportunity_level": "high_priority",
        },
        incident_id="incident:fixture-spacex",
        hypothesis_id="hypothesis:fixture-velvet-spacex",
        should_alert=True,
        material_change_reasons=("fixture_notification_smoke",),
    )


def _aave_entry(now: datetime) -> event_watchlist.EventWatchlistEntry:
    return event_watchlist.EventWatchlistEntry(
        schema_version=event_watchlist.WATCHLIST_SCHEMA_VERSION,
        row_type="event_watchlist_state",
        key="fixture-aave-kraken|aave|strategic_investment",
        cluster_id="fixture-aave-kraken|strategic_investment|2026-06-15",
        event_id="fixture-notify-aave",
        coin_id="aave",
        symbol="AAVE",
        relationship_type="strategic_investment",
        external_asset="Kraken",
        event_time=None,
        state=event_watchlist.EventWatchlistState.RADAR.value,
        previous_state=None,
        first_seen_at=now.isoformat(),
        last_seen_at=now.isoformat(),
        source_count=2,
        highest_score=78,
        latest_score=78,
        latest_tier="WATCHLIST",
        latest_event_name="Kraken takes strategic stake in Aave ecosystem",
        latest_source="Crypto news fixture",
        latest_playbook_type="strategic_investment_or_valuation",
        latest_rule_playbook_type="strategic_investment_or_valuation",
        latest_effective_playbook_type="strategic_investment_or_valuation",
        latest_playbook_score=78,
        latest_playbook_action="watchlist",
        latest_market_snapshot={},
        latest_score_components={
            "core_opportunity_id": "agg:fixture-aave-kraken",
            "hypothesis_id": "hypothesis:fixture-aave-kraken",
            "impact_path_type": "strategic_investment_or_valuation",
            "impact_path_reason": "strategic_investment",
            "candidate_role": "direct_subject",
            "source_class": "crypto_news",
            "evidence_specificity": "direct_token_mechanism",
            "evidence_acquisition_status": "accepted_evidence_found",
            "accepted_evidence_count": 1,
            "market_confirmation_level": "none",
            "market_context_freshness_status": "missing",
            "opportunity_level": "validated_digest",
            "opportunity_score_final": 78,
        },
        incident_id="incident:fixture-aave-kraken",
        hypothesis_id="hypothesis:fixture-aave-kraken",
        should_alert=True,
        material_change_reasons=("fixture_notification_digest",),
    )


def _route_decision(
    entry: event_watchlist.EventWatchlistEntry,
    *,
    route: event_alpha_router.EventAlphaRoute,
    lane: event_alpha_router.EventAlphaRouteLane,
    alertable: bool,
    reason: str,
) -> event_alpha_router.EventAlphaRouteDecision:
    return event_alpha_router.EventAlphaRouteDecision(
        entry=entry,
        route=route,
        alertable=alertable,
        reason=reason,
        lane=lane,
    )


def build_primary_notification_fixtures(now: datetime) -> dict[str, Any]:
    entry = _velvet_entry(now)
    aave_entry = _aave_entry(now)
    return {
        "entry": entry,
        "decision": _route_decision(
            entry,
            route=event_alpha_router.EventAlphaRoute.HIGH_PRIORITY_RESEARCH,
            lane=event_alpha_router.EventAlphaRouteLane.INSTANT_ESCALATION,
            alertable=True,
            reason="Fixture high-priority state escalation for notification smoke.",
        ),
        "aave_entry": aave_entry,
        "aave_decision": _route_decision(
            aave_entry,
            route=event_alpha_router.EventAlphaRoute.RESEARCH_DIGEST,
            lane=event_alpha_router.EventAlphaRouteLane.DAILY_DIGEST,
            alertable=True,
            reason="Fixture accepted source evidence for strategic stake digest.",
        ),
    }

def _velvet_core_row(entry: event_watchlist.EventWatchlistEntry) -> dict[str, Any]:
    return {
        "row_type": "event_impact_hypothesis",
        "core_opportunity_id": "agg:fixture-velvet-spacex",
        "key": entry.key,
        "hypothesis_id": entry.hypothesis_id,
        "incident_id": entry.incident_id,
        "event_id": entry.event_id,
        "symbol": entry.symbol,
        "coin_id": entry.coin_id,
        "validated_symbol": entry.symbol,
        "validated_coin_id": entry.coin_id,
        "canonical_incident_name": entry.latest_event_name,
        "candidate_role": "proxy_venue",
        "impact_category": "proxy_attention",
        "impact_path_type": "venue_value_capture",
        "impact_path_strength": "strong",
        "impact_path_reason": "venue_value_capture",
        "relationship_type": "venue_value_capture",
        "opportunity_level": "high_priority",
        "final_opportunity_level": "high_priority",
        "opportunity_score_final": 92,
        "final_route_after_quality_gate": event_alpha_router.EventAlphaRoute.HIGH_PRIORITY_RESEARCH.value,
        "final_state_after_quality_gate": event_watchlist.EventWatchlistState.HIGH_PRIORITY.value,
        "source_class": "cryptopanic_tagged",
        "evidence_specificity": "direct_token_mechanism",
        "evidence_quality_score": 91,
        "market_confirmation_score": 88,
        "market_confirmation_level": "strong",
        "market_context_freshness_status": "fresh",
        "market_context_source": "fixture_market_context",
        "evidence_acquisition_status": "accepted_evidence_found",
        "evidence_acquisition_accepted_count": 1,
        "accepted_evidence_count": 1,
        "acquisition_confirmation_status": "confirms",
        "accepted_evidence_reason_codes": ["cryptopanic_currency_tag_match", "direct_token_mechanism"],
        "accepted_evidence_samples": [
            {
                "title": "VELVET offers SpaceX pre-IPO tokenized stock exposure",
                "provider": "cryptopanic_fixture",
                "source_url": "https://example.invalid/velvet-spacex",
            }
        ],
        "source_pack": "proxy_preipo_rwa_pack",
        "latest_source": "CryptoPanic fixture",
        "latest_source_title": "VELVET offers SpaceX pre-IPO tokenized stock exposure",
        "why_opportunity_visible": "Accepted tagged evidence validates the token/catalyst link.",
        "upgrade_requirements": ["verify accepted source evidence", "confirm market reaction remains organic"],
        "latest_market_snapshot": entry.latest_market_snapshot,
    }


def _btc_control_core_row() -> dict[str, Any]:
    return {
        "row_type": "event_impact_hypothesis",
        "core_opportunity_id": "agg:fixture-btc-rejected",
        "key": "fixture-strategy|bitcoin|strategic_context",
        "hypothesis_id": "hypothesis:fixture-btc-rejected",
        "incident_id": "incident:fixture-strategy-valuation",
        "symbol": "BTC",
        "coin_id": "bitcoin",
        "validated_symbol": "BTC",
        "validated_coin_id": "bitcoin",
        "canonical_incident_name": "Strategy valuation article mentions Bitcoin treasury holdings",
        "candidate_role": "treasury_context",
        "impact_category": "strategic_investment_or_valuation",
        "impact_path_type": "strategic_investment_or_valuation",
        "impact_path_strength": "medium",
        "impact_path_reason": "treasury_context",
        "opportunity_level": "local_only",
        "final_opportunity_level": "local_only",
        "opportunity_score_final": 44,
        "final_route_after_quality_gate": event_alpha_router.EventAlphaRoute.STORE_ONLY.value,
        "final_state_after_quality_gate": event_watchlist.EventWatchlistState.RAW_EVIDENCE.value,
        "source_class": "crypto_news",
        "evidence_specificity": "direct_token_mechanism",
        "evidence_quality_score": 88,
        "market_confirmation_score": 0,
        "market_confirmation_level": "none",
        "market_context_freshness_status": "missing",
        "evidence_acquisition_status": "rejected_results_only",
        "evidence_acquisition_rejected_count": 2,
        "accepted_evidence_count": 0,
        "acquisition_confirmation_status": "does_not_confirm",
        "source_pack": "strategic_investment_pack",
        "latest_source": "Strategy valuation fixture",
        "why_opportunity_visible": "Fixture control: broad treasury valuation context is not direct BTC confirmation.",
    }


def _aave_core_row(aave_entry: event_watchlist.EventWatchlistEntry) -> dict[str, Any]:
    return {
        "row_type": "event_impact_hypothesis",
        "core_opportunity_id": "agg:fixture-aave-kraken",
        "key": aave_entry.key,
        "hypothesis_id": aave_entry.hypothesis_id,
        "incident_id": aave_entry.incident_id,
        "event_id": aave_entry.event_id,
        "symbol": aave_entry.symbol,
        "coin_id": aave_entry.coin_id,
        "validated_symbol": aave_entry.symbol,
        "validated_coin_id": aave_entry.coin_id,
        "canonical_incident_name": aave_entry.latest_event_name,
        "candidate_role": "direct_subject",
        "impact_category": "strategic_investment_or_valuation",
        "impact_path_type": "strategic_investment_or_valuation",
        "impact_path_strength": "medium",
        "impact_path_reason": "strategic_investment",
        "relationship_type": "strategic_investment",
        "opportunity_level": "validated_digest",
        "final_opportunity_level": "validated_digest",
        "opportunity_score_final": 78,
        "final_route_after_quality_gate": event_alpha_router.EventAlphaRoute.RESEARCH_DIGEST.value,
        "final_state_after_quality_gate": event_watchlist.EventWatchlistState.RADAR.value,
        "source_class": "crypto_news",
        "evidence_specificity": "direct_token_mechanism",
        "evidence_quality_score": 86,
        "market_confirmation_score": 0,
        "market_confirmation_level": "none",
        "market_context_freshness_status": "missing",
        "evidence_acquisition_status": "accepted_evidence_found",
        "evidence_acquisition_accepted_count": 1,
        "accepted_evidence_count": 1,
        "acquisition_confirmation_status": "confirms",
        "accepted_evidence_reason_codes": ["direct_token_mechanism"],
        "accepted_evidence_samples": [
            {
                "title": "Kraken takes strategic stake in Aave ecosystem",
                "provider": "crypto_news_fixture",
                "source_url": "https://example.invalid/aave-kraken",
            }
        ],
        "source_pack": "strategic_investment_pack",
        "latest_source": "Crypto news fixture",
        "latest_source_title": "Kraken takes strategic stake in Aave ecosystem",
        "why_opportunity_visible": "Accepted direct source evidence validates the AAVE/Kraken relationship.",
        "upgrade_requirements": ["verify primary source", "wait for market confirmation"],
    }


def _tao_control_core_row() -> dict[str, Any]:
    return {
        "row_type": "event_impact_hypothesis",
        "core_opportunity_id": "agg:fixture-tao-rejected",
        "key": "fixture-tao|bittensor|strategic_context",
        "hypothesis_id": "hypothesis:fixture-tao-rejected",
        "incident_id": "incident:fixture-tao-strategic",
        "symbol": "TAO",
        "coin_id": "bittensor",
        "validated_symbol": "TAO",
        "validated_coin_id": "bittensor",
        "canonical_incident_name": "Broad AI infrastructure article mentions Bittensor without impact evidence",
        "candidate_role": "direct_subject",
        "impact_category": "strategic_investment_or_valuation",
        "impact_path_type": "strategic_investment_or_valuation",
        "impact_path_strength": "weak",
        "impact_path_reason": "weak_cooccurrence_only",
        "opportunity_level": "local_only",
        "final_opportunity_level": "local_only",
        "opportunity_score_final": 38,
        "final_route_after_quality_gate": event_alpha_router.EventAlphaRoute.STORE_ONLY.value,
        "final_state_after_quality_gate": event_watchlist.EventWatchlistState.RAW_EVIDENCE.value,
        "source_class": "broad_news",
        "evidence_specificity": "weak_cooccurrence",
        "evidence_quality_score": 40,
        "market_confirmation_score": 0,
        "market_confirmation_level": "none",
        "market_context_freshness_status": "missing",
        "evidence_acquisition_status": "rejected_results_only",
        "evidence_acquisition_rejected_count": 1,
        "accepted_evidence_count": 0,
        "acquisition_confirmation_status": "does_not_confirm",
        "source_pack": "strategic_investment_pack",
        "latest_source": "Broad AI fixture",
        "why_opportunity_visible": "Fixture control: broad AI/TAO co-occurrence is not validated impact evidence.",
    }


def _doge_near_miss_core_row() -> dict[str, Any]:
    return {
        "row_type": "event_impact_hypothesis",
        "core_opportunity_id": "agg:fixture-doge-near-miss",
        "key": "fixture-doge|dogecoin|exploratory_meme_catalyst",
        "hypothesis_id": "hypothesis:fixture-doge-near-miss",
        "incident_id": "incident:fixture-doge-catalyst",
        "symbol": "DOGE",
        "coin_id": "dogecoin",
        "validated_symbol": "DOGE",
        "validated_coin_id": "dogecoin",
        "canonical_incident_name": "DOGE jumps on unconfirmed meme catalyst chatter",
        "candidate_role": "candidate_asset",
        "impact_category": "meme_attention",
        "impact_path_type": "meme_attention",
        "impact_path_strength": "medium",
        "impact_path_reason": "market_confirmation_without_source_confirmation",
        "relationship_type": "proxy_attention",
        "opportunity_level": "exploratory",
        "final_opportunity_level": "exploratory",
        "opportunity_score_final": 66,
        "final_route_after_quality_gate": event_alpha_router.EventAlphaRoute.STORE_ONLY.value,
        "final_state_after_quality_gate": event_watchlist.EventWatchlistState.RAW_EVIDENCE.value,
        "source_class": "crypto_news",
        "evidence_specificity": "candidate_context",
        "evidence_quality_score": 58,
        "market_confirmation_score": 72,
        "market_confirmation_level": "moderate",
        "market_context_freshness_status": "fresh",
        "evidence_acquisition_status": "skipped_budget",
        "accepted_evidence_count": 0,
        "acquisition_confirmation_status": "unresolved",
        "source_pack": "meme_attention_pack",
        "latest_source": "Meme catalyst fixture",
        "latest_source_title": "DOGE jumps on unconfirmed meme catalyst chatter",
        "why_opportunity_visible": "Strong fresh move with a possible catalyst clue, but no independent confirmation yet.",
        "why_not_watchlist": "missing independent source confirmation",
        "upgrade_requirements": ["find independent catalyst evidence", "verify liquidity and organic volume"],
    }


def build_core_fixture_rows(
    entry: event_watchlist.EventWatchlistEntry,
    aave_entry: event_watchlist.EventWatchlistEntry,
) -> list[dict[str, Any]]:
    return [
        _velvet_core_row(entry),
        _aave_core_row(aave_entry),
        _btc_control_core_row(),
        _tao_control_core_row(),
        _doge_near_miss_core_row(),
    ]


def _control_entry(
    now: datetime,
    *,
    key: str,
    cluster_id: str,
    event_id: str,
    coin_id: str,
    symbol: str,
    external_asset: str,
    latest_event_name: str,
    latest_source: str,
    playbook_type: str,
    score: int,
    latest_market_snapshot: dict[str, Any],
    latest_score_components: dict[str, Any],
    incident_id: str,
    hypothesis_id: str,
    suppressed_reason: str,
) -> event_watchlist.EventWatchlistEntry:
    return event_watchlist.EventWatchlistEntry(
        schema_version=event_watchlist.WATCHLIST_SCHEMA_VERSION,
        row_type="event_watchlist_state",
        key=key,
        cluster_id=cluster_id,
        event_id=event_id,
        coin_id=coin_id,
        symbol=symbol,
        relationship_type=playbook_type,
        external_asset=external_asset,
        event_time=None,
        state=event_watchlist.EventWatchlistState.RAW_EVIDENCE.value,
        previous_state=None,
        first_seen_at=now.isoformat(),
        last_seen_at=now.isoformat(),
        source_count=1,
        highest_score=score,
        latest_score=score,
        latest_tier="STORE_ONLY",
        latest_event_name=latest_event_name,
        latest_source=latest_source,
        latest_playbook_type=playbook_type,
        latest_rule_playbook_type=playbook_type,
        latest_effective_playbook_type=playbook_type,
        latest_playbook_score=score,
        latest_playbook_action="store_only",
        latest_market_snapshot=latest_market_snapshot,
        latest_score_components=latest_score_components,
        incident_id=incident_id,
        hypothesis_id=hypothesis_id,
        should_alert=False,
        suppressed_reason=suppressed_reason,
    )


def build_control_notification_fixtures(now: datetime) -> dict[str, Any]:
    btc_entry = _control_entry(
        now,
        key="fixture-strategy|bitcoin|strategic_context",
        cluster_id="fixture-strategy|strategic_context|2026-06-15",
        event_id="fixture-btc-rejected",
        coin_id="bitcoin",
        symbol="BTC",
        external_asset="Strategy",
        latest_event_name="Strategy valuation article mentions Bitcoin treasury holdings",
        latest_source="Strategy valuation fixture",
        playbook_type="strategic_investment_or_valuation",
        score=44,
        latest_market_snapshot={},
        latest_score_components={
            "core_opportunity_id": "agg:fixture-btc-rejected",
            "hypothesis_id": "hypothesis:fixture-btc-rejected",
            "impact_path_type": "strategic_investment_or_valuation",
            "impact_path_reason": "treasury_context",
            "candidate_role": "treasury_context",
            "source_class": "crypto_news",
            "evidence_acquisition_status": "rejected_results_only",
            "accepted_evidence_count": 0,
            "market_confirmation_level": "none",
            "market_context_freshness_status": "missing",
            "opportunity_level": "local_only",
            "opportunity_score_final": 44,
        },
        incident_id="incident:fixture-strategy-valuation",
        hypothesis_id="hypothesis:fixture-btc-rejected",
        suppressed_reason="rejected_results_only_not_confirmation",
    )
    tao_entry = _control_entry(
        now,
        key="fixture-tao|bittensor|strategic_context",
        cluster_id="fixture-tao|strategic_context|2026-06-15",
        event_id="fixture-tao-rejected",
        coin_id="bittensor",
        symbol="TAO",
        external_asset="AI infrastructure",
        latest_event_name="Broad AI infrastructure article mentions Bittensor without impact evidence",
        latest_source="Broad AI fixture",
        playbook_type="strategic_investment_or_valuation",
        score=38,
        latest_market_snapshot={},
        latest_score_components={
            "core_opportunity_id": "agg:fixture-tao-rejected",
            "hypothesis_id": "hypothesis:fixture-tao-rejected",
            "impact_path_type": "strategic_investment_or_valuation",
            "impact_path_reason": "weak_cooccurrence_only",
            "candidate_role": "direct_subject",
            "source_class": "broad_news",
            "evidence_acquisition_status": "rejected_results_only",
            "accepted_evidence_count": 0,
            "market_confirmation_level": "none",
            "market_context_freshness_status": "missing",
            "opportunity_level": "local_only",
            "opportunity_score_final": 38,
        },
        incident_id="incident:fixture-tao-strategic",
        hypothesis_id="hypothesis:fixture-tao-rejected",
        suppressed_reason="rejected_results_only_not_confirmation",
    )
    doge_entry = _control_entry(
        now,
        key="fixture-doge|dogecoin|exploratory_meme_catalyst",
        cluster_id="fixture-doge|meme_attention|2026-06-15",
        event_id="fixture-doge-near-miss",
        coin_id="dogecoin",
        symbol="DOGE",
        external_asset="meme catalyst chatter",
        latest_event_name="DOGE jumps on unconfirmed meme catalyst chatter",
        latest_source="Meme catalyst fixture",
        playbook_type="meme_attention",
        score=66,
        latest_market_snapshot={"return_24h": 0.31, "return_72h": 0.66, "volume_mcap": 0.22},
        latest_score_components={
            "core_opportunity_id": "agg:fixture-doge-near-miss",
            "hypothesis_id": "hypothesis:fixture-doge-near-miss",
            "impact_path_type": "meme_attention",
            "impact_path_reason": "market_confirmation_without_source_confirmation",
            "candidate_role": "candidate_asset",
            "source_class": "crypto_news",
            "evidence_acquisition_status": "skipped_budget",
            "accepted_evidence_count": 0,
            "market_confirmation_score": 72,
            "market_confirmation_level": "moderate",
            "market_context_freshness_status": "fresh",
            "opportunity_level": "exploratory",
            "opportunity_score_final": 66,
            "why_not_watchlist": "missing independent source confirmation",
            "upgrade_requirements": ["find independent catalyst evidence", "verify liquidity and organic volume"],
        },
        incident_id="incident:fixture-doge-catalyst",
        hypothesis_id="hypothesis:fixture-doge-near-miss",
        suppressed_reason="missing independent source confirmation",
    )
    return {
        "btc_entry": btc_entry,
        "btc_decision": _route_decision(
            btc_entry,
            route=event_alpha_router.EventAlphaRoute.STORE_ONLY,
            lane=event_alpha_router.EventAlphaRouteLane.LOCAL_ONLY,
            alertable=False,
            reason="Fixture control: rejected-only strategic broad-asset context is local-only.",
        ),
        "tao_entry": tao_entry,
        "tao_decision": _route_decision(
            tao_entry,
            route=event_alpha_router.EventAlphaRoute.STORE_ONLY,
            lane=event_alpha_router.EventAlphaRouteLane.LOCAL_ONLY,
            alertable=False,
            reason="Fixture control: rejected-only TAO context is local-only.",
        ),
        "doge_entry": doge_entry,
        "doge_decision": _route_decision(
            doge_entry,
            route=event_alpha_router.EventAlphaRoute.STORE_ONLY,
            lane=event_alpha_router.EventAlphaRouteLane.LOCAL_ONLY,
            alertable=False,
            reason="Fixture near-miss: strong move needs independent catalyst confirmation.",
        ),
    }
